/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BankRoutingInfo } from './bank-routing-info';
// May contain unused imports in some cases
// @ts-ignore
import type { BeneficiaryAccountDetailsDTO } from './beneficiary-account-details-dto';

/**
 * 
 * @export
 * @interface AccountValidationRequestDTO
 */
export interface AccountValidationRequestDTO {
    /**
     * The bank account number which needs to be verified.
     * @type {string}
     * @memberof AccountValidationRequestDTO
     */
    'accountNumber'?: string;
    /**
     * The type of account.
     * @type {string}
     * @memberof AccountValidationRequestDTO
     */
    'bankAccountType': AccountValidationRequestDTOBankAccountTypeEnum;
    /**
     * The bank code of the beneficiary. E.g: The bank code for England is GB. Note: This field is mandatory when the destination country is Pakistan (PK).
     * @type {string}
     * @memberof AccountValidationRequestDTO
     */
    'bankCode'?: string;
    /**
     * 
     * @type {BeneficiaryAccountDetailsDTO}
     * @memberof AccountValidationRequestDTO
     */
    'beneficiary'?: BeneficiaryAccountDetailsDTO;
    /**
     * This field accepts the 2-letter [ISO-2 country code](https://docs.nium.com/apis/docs/currency-and-country-codes) of the destination country.
     * @type {string}
     * @memberof AccountValidationRequestDTO
     */
    'destinationCountry'?: string;
    /**
     * The 3-letter ISO-3 currency code of the bank account.
     * @type {string}
     * @memberof AccountValidationRequestDTO
     */
    'destinationCurrency': string;
    /**
     * The different payout modes that\'ll be used by the beneficiary.
     * @type {string}
     * @memberof AccountValidationRequestDTO
     */
    'payoutMethod': AccountValidationRequestDTOPayoutMethodEnum;
    /**
     * <p>Specifies the proxy type sent in the payment request:</p> <ul>   <li><strong>SGD-PayNow:</strong> The proxy type can be <code>MOBILE</code>, <code>UEN</code>, or <code>NRIC</code></li>   <li><strong>INR-UPI:</strong> The proxy type is <code>VPA</code></li>   <li><strong>MYR-DuitNow:</strong> The proxy type can be <code>NRIC</code>, <code>PASSPORT</code>, <code>CORPORATE_REGISTRATION_NUMBER</code>, <code>MOBILE</code>, or <code>ARMY_ID</code></li> </ul> <p><strong>Note:</strong> This field is mandatory when the payout method type is <code>PROXY</code>.</p> 
     * @type {string}
     * @memberof AccountValidationRequestDTO
     */
    'proxyType'?: string;
    /**
     * <p>The available proxy values. This can include VPA, UEN, or a mobile number.</p> <p><strong>Note:</strong> This field is mandatory when the payout method type is <code>PROXY</code>.</p> <p>Mobile number must include country code.</p> 
     * @type {string}
     * @memberof AccountValidationRequestDTO
     */
    'proxyValue'?: string;
    /**
     * 
     * @type {Array<BankRoutingInfo>}
     * @memberof AccountValidationRequestDTO
     */
    'routingInfo'?: Array<BankRoutingInfo>;
}

export const AccountValidationRequestDTOBankAccountTypeEnum = {
    Checking: 'CHECKING',
    Saving: 'SAVING',
    Maestra: 'MAESTRA',
    Current: 'CURRENT'
} as const;

export type AccountValidationRequestDTOBankAccountTypeEnum = typeof AccountValidationRequestDTOBankAccountTypeEnum[keyof typeof AccountValidationRequestDTOBankAccountTypeEnum];
export const AccountValidationRequestDTOPayoutMethodEnum = {
    Card: 'CARD',
    Wallet: 'WALLET',
    Cash: 'CASH',
    Swift: 'SWIFT',
    Local: 'LOCAL',
    Proxy: 'PROXY',
    Fedwire: 'FEDWIRE',
    Check: 'CHECK'
} as const;

export type AccountValidationRequestDTOPayoutMethodEnum = typeof AccountValidationRequestDTOPayoutMethodEnum[keyof typeof AccountValidationRequestDTOPayoutMethodEnum];


