/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ActivateCardResponseDTO
 */
export interface ActivateCardResponseDTO {
    /**
     * This field shows the status of the activation request.
     * @type {string}
     * @memberof ActivateCardResponseDTO
     */
    'status'?: string;
}

