/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddCardRequestPHY } from './add-card-request-phy';
// May contain unused imports in some cases
// @ts-ignore
import { AddCardRequestVIR } from './add-card-request-vir';
// May contain unused imports in some cases
// @ts-ignore
import { CardAddress } from './card-address';

/**
 * @type AddCardRequestVIRUP2PHY
 * @export
 */
export type AddCardRequestVIRUP2PHY = AddCardRequestPHY & AddCardRequestVIR;


