/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddCustomerRequestDTO } from './add-customer-request-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ComplianceIdentificationDocDTO } from './compliance-identification-doc-dto';
// May contain unused imports in some cases
// @ts-ignore
import { CustomerTagDTO } from './customer-tag-dto';
// May contain unused imports in some cases
// @ts-ignore
import { CustomerTaxDetailDTO } from './customer-tax-detail-dto';

/**
 * @type AddCustomerChildMustHaveParentWithCorpBilling
 * @export
 */
export type AddCustomerChildMustHaveParentWithCorpBilling = AddCustomerRequestDTO;


