/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TypedErrorOfstring } from './typed-error-ofstring';

/**
 * 
 * @export
 * @interface AddFundingInstrumentV2ErrorResponse
 */
export interface AddFundingInstrumentV2ErrorResponse {
    /**
     * 
     * @type {Array<TypedErrorOfstring>}
     * @memberof AddFundingInstrumentV2ErrorResponse
     */
    'errors'?: Array<TypedErrorOfstring>;
}

