/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BusinessAddress } from './business-address';
// May contain unused imports in some cases
// @ts-ignore
import type { RegisteredAddress } from './registered-address';

/**
 * 
 * @export
 * @interface Addresses
 */
export interface Addresses {
    /**
     * 
     * @type {BusinessAddress}
     * @memberof Addresses
     */
    'businessAddress'?: BusinessAddress;
    /**
     * 
     * @type {RegisteredAddress}
     * @memberof Addresses
     */
    'registeredAddress'?: RegisteredAddress;
}

