/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiError2
 */
export interface ApiError2 {
    /**
     * Returns the errors that occurred if any.
     * @type {Array<string>}
     * @memberof ApiError2
     */
    'errors'?: Array<string>;
    /**
     * Provides more details about the returned error, if any.
     * @type {string}
     * @memberof ApiError2
     */
    'message'?: string;
}

