/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AssociationDetails
 */
export interface AssociationDetails {
    /**
     * The full name of the association chair, secretary, or treasurer.
     * @type {string}
     * @memberof AssociationDetails
     */
    'associationChairPerson'?: string;
    /**
     * The complete name of the association.
     * @type {string}
     * @memberof AssociationDetails
     */
    'associationName'?: string;
    /**
     * The association number as issued by the applicable state or territory.
     * @type {string}
     * @memberof AssociationDetails
     */
    'associationNumber'?: string;
}

