/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BankRoutingInfo
 */
export interface BankRoutingInfo {
    /**
     * The routing code type.
     * @type {string}
     * @memberof BankRoutingInfo
     */
    'type'?: BankRoutingInfoTypeEnum;
    /**
     * <p>Accepts the routing code value 1. Examples include:</p> <ul>   <li><code>ADCBINBB</code> or <code>ADCBINBB123</code> for SWIFT</li>   <li><code>SBIN0000058</code> for IFSC</li>   <li><code>100000</code> for SORT CODE</li>   <li><code>111000025</code> for ACH CODE</li>   <li><code>012515</code> for BSB CODE</li>   <li><code>151</code> for BANK CODE</li> </ul> <p>If you have any questions, please reach out to your Nium account manager or <a href=\"mailto:support@nium. 
     * @type {string}
     * @memberof BankRoutingInfo
     */
    'value'?: string;
}

export const BankRoutingInfoTypeEnum = {
    Ifsc: 'IFSC',
    Swift: 'SWIFT',
    AchCode: 'ACH_CODE',
    BsbCode: 'BSB_CODE',
    SortCode: 'SORT_CODE',
    BankCode: 'BANK_CODE',
    LocationId: 'LOCATION_ID',
    BranchCode: 'BRANCH_CODE',
    TransitNumber: 'TRANSIT_NUMBER',
    BranchName: 'BRANCH_NAME',
    Cnaps: 'CNAPS',
    Wallet: 'WALLET'
} as const;

export type BankRoutingInfoTypeEnum = typeof BankRoutingInfoTypeEnum[keyof typeof BankRoutingInfoTypeEnum];


