/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2025.9.9
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BeneficiaryAccountDetailsDTO
 */
export interface BeneficiaryAccountDetailsDTO {
    /**
     * This field accepts the name of a beneficiary.
     * @type {string}
     * @memberof BeneficiaryAccountDetailsDTO
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryAccountDetailsDTO
     */
    'alias'?: string;
    /**
     * Full residential address of the beneficiary.
     * @type {string}
     * @memberof BeneficiaryAccountDetailsDTO
     */
    'address'?: string;
    /**
     * City where the beneficiary lives.
     * @type {string}
     * @memberof BeneficiaryAccountDetailsDTO
     */
    'city'?: string;
    /**
     * This field accepts an email of the beneficiary.
     * @type {string}
     * @memberof BeneficiaryAccountDetailsDTO
     */
    'email'?: string;
    /**
     * This field accepts the bank account type of the beneficiary.
     * @type {string}
     * @memberof BeneficiaryAccountDetailsDTO
     */
    'accountType'?: string;
    /**
     * This field accepts the mobile number of the beneficiary.
     * @type {string}
     * @memberof BeneficiaryAccountDetailsDTO
     */
    'contactNumber'?: string;
    /**
     * State or province of the beneficiary\'s address.
     * @type {string}
     * @memberof BeneficiaryAccountDetailsDTO
     */
    'state'?: string;
    /**
     * This field accepts an postcode of the beneficiary.
     * @type {string}
     * @memberof BeneficiaryAccountDetailsDTO
     */
    'postcode'?: string;
    /**
     * This field accepts the [ISO-2 country code](https://docs.nium.com/apis/docs/currency-and-country-codes) for the mobile number of beneficiary.
     * @type {string}
     * @memberof BeneficiaryAccountDetailsDTO
     */
    'countryCode'?: string;
    /**
     * This field accepts the relationship of the beneficiary with the remitter.
     * @type {string}
     * @memberof BeneficiaryAccountDetailsDTO
     */
    'remitterBeneficiaryRelationship'?: string;
    /**
     * This field accepts the type of identification document name for a beneficiary.
     * @type {string}
     * @memberof BeneficiaryAccountDetailsDTO
     */
    'beneficiaryIdentificationType'?: string;
    /**
     * This field contains an identification document number for the beneficiary.
     * @type {string}
     * @memberof BeneficiaryAccountDetailsDTO
     */
    'beneficiaryIdentificationValue'?: string;
}

