/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2026.4.14
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RoutingCode } from './routing-code';

export interface BeneficiaryPaymentAccount {
    /**
     * A possible values of a bank account type of a beneficiary.
     */
    'accountType'?: BeneficiaryPaymentAccountAccountTypeEnum;
    /**
     * A bank name of a beneficiary.
     */
    'bankName'?: string;
    /**
     * A bank account code of a beneficiary.
     */
    'bankCode'?: string;
    /**
     * A bank swift account number of a beneficiary.
     */
    'accountNumber'?: string;
    /**
     * A possible values of payment account types of a beneficiary.
     */
    'payoutMethod'?: string;
    /**
     * A 3-letter ISO-4217 currency code.
     */
    'payoutCurrency'?: string;
    /**
     * A routing code details
     */
    'routingCode'?: Array<RoutingCode>;
    /**
     * This field indicates the proxy type sent in the request.  For SGD-PayNow: The proxy type can be MOBILE, UEN , or NRIC For INR-UPI: The proxy type should be VPA  For MYR-DuitNow: The proxy type can be NRIC, PASSPORT, CORPORATE_REGISTRATION_NUMBER, MOBILE, or ARMY_ID Note : This field is mandatory when the payoutMethod type is PROXY.
     */
    'proxyType'?: string;
    /**
     * This field indicates the proxy value such as VPA, UEN, or mobile number etc. Note: This field is mandatory when the payoutMethod type is PROXY The mobile number should include country code.
     */
    'proxyValue'?: string;
}

export const BeneficiaryPaymentAccountAccountTypeEnum = {
    Checking: 'CHECKING',
    Saving: 'SAVING',
    Maestra: 'MAESTRA',
    Current: 'CURRENT',
} as const;

export type BeneficiaryPaymentAccountAccountTypeEnum = typeof BeneficiaryPaymentAccountAccountTypeEnum[keyof typeof BeneficiaryPaymentAccountAccountTypeEnum];


