/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BeneficiaryValidationResponseDTO
 */
export interface BeneficiaryValidationResponseDTO {
    /**
     * This field contains beneficiary bank code if the payout method is proxy and proxy type is VPA.
     * @type {string}
     * @memberof BeneficiaryValidationResponseDTO
     */
    'beneficiaryBankCode'?: string;
    /**
     * This field contains beneficiary name if the payout method is proxy.
     * @type {string}
     * @memberof BeneficiaryValidationResponseDTO
     */
    'beneficiaryName'?: string;
    /**
     * This field contains the status only when the proxy type is VPA. The possible values are: VE: Virtual Address Available F: Failed VN: Virtual Address not Available
     * @type {string}
     * @memberof BeneficiaryValidationResponseDTO
     */
    'status'?: string;
    /**
     * This field will return true if the provided details are valid otherwise false.
     * @type {boolean}
     * @memberof BeneficiaryValidationResponseDTO
     */
    'valid'?: boolean;
}

