/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2026.4.14
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Accepts the payout details.
 */
export interface BulkPayoutServicePayout {
    /**
     * Accepts the swift fee type and defines who will bear the SWIFT charges for the transaction.  Clients can send any of the following values basis which, they will be charged for the SWIFT transaction. If this field is left blank `SHA` will be used by default.   - **SHA**: SWIFT charges shared by the customer and beneficiary.   - **OUR**: SWIFT charges borne by the customer.  Clients should make sure that fee template is configured for each SWIFT fee type. Use the [Fetch Fee Details](/api#tag/client-settings/GET/api/v3/client/{clientHashId}/fees) request to verify the templates are configuered correctly.
     */
    'swiftFeeType'?: BulkPayoutServicePayoutSwiftFeeTypeEnum;
    /**
     * The scheduled payout date in yyyy-MM-dd format
     */
    'scheduledPayoutDate'?: string;
    /**
     * Denote the invoice number relevant to the transaction.
     */
    'tradeOrderID'?: string;
    /**
     * The date service/export was or will be provided (in `yyyy-MM-dd` format).
     */
    'serviceTime'?: string;
    /**
     * Indicates if compliance checks are to be done at the time of payout creation.  This field is applicable for Scheduled or Post-funded payouts only.
     */
    'preScreening'?: boolean;
    /**
     * The audit Id must be taken from the response to the [Exchange Rate Lock and Hold](https://docs.nium.com/baas/exchange-rate-lock-and-hold) request. Note: This field name can also be passed as `audit_id`.
     */
    'auditId'?: number;
    /**
     * This field accepts the source amount for `remittance`. Either the source or the destination amount is required.  Allowed decimal limit is 2. Note: This field name can also be passed as `source_amount`.
     */
    'sourceAmount'?: number;
    /**
     * The source currency for the `remittance`. Note: This field name can also be passed as `source_currency`.
     */
    'sourceCurrency'?: string;
    /**
     * The payout currency for the `remittance`. Note: This field name can also be passed as `payout_currency`.
     */
    'payoutCurrency': string;
    /**
     * The destination amount for the `remittance`. Either the source or the destination amount is required.   - Allowed decimal limit is 2.   - This field name can also be passed as destination_amount.
     */
    'destinationAmount'?: number;
}

export const BulkPayoutServicePayoutSwiftFeeTypeEnum = {
    Our: 'OUR',
    Sha: 'SHA',
} as const;

export type BulkPayoutServicePayoutSwiftFeeTypeEnum = typeof BulkPayoutServicePayoutSwiftFeeTypeEnum[keyof typeof BulkPayoutServicePayoutSwiftFeeTypeEnum];


