/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2025.9.9
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Card details
 * @export
 * @interface CardInfo
 */
export interface CardInfo {
    /**
     * Pre-defined product Id, defined at Nium and communicated to client for card issuance.
     * @type {string}
     * @memberof CardInfo
     */
    'cardProductId'?: string;
    /**
     * This field contains the pre-defined plastic Id which is used to determine card design.
     * @type {string}
     * @memberof CardInfo
     */
    'plasticId'?: string;
    /**
     * This field contains the 2-letter [region code](/docs/currency-and-country-codes) for the card.
     * @type {string}
     * @memberof CardInfo
     */
    'regionCode'?: string;
    /**
     * This field contains the 16-digit masked card number in format 1234-56xx-xxxx-3456.
     * @type {string}
     * @memberof CardInfo
     */
    'maskedCardNumber'?: string;
    /**
     * This field contains the reference number for the card.
     * @type {string}
     * @memberof CardInfo
     */
    'proxyNumber'?: string;
    /**
     * This field contains the issued card type.
     * @type {string}
     * @memberof CardInfo
     */
    'cardType'?: string;
    /**
     * This field contains the type of the card issued.
     * @type {string}
     * @memberof CardInfo
     */
    'issuanceType'?: string;
    /**
     * This field contains the activation status of the card.
     * @type {string}
     * @memberof CardInfo
     */
    'cardStatus'?: CardInfoCardStatusEnum;
    /**
     * Unique ID for an individual customer linked to a parent-level corporate customer. Used to associate and track the child customer within a corporate customer\'s program.
     * @type {string}
     * @memberof CardInfo
     */
    'childCustomerHashId'?: string;
}

export const CardInfoCardStatusEnum = {
    InactiveactivevirtualActivetempBlockpBlock: 'INACTIVE,ACTIVE,VIRTUAL_ACTIVE,TEMP_BLOCK,P_BLOCK'
} as const;

export type CardInfoCardStatusEnum = typeof CardInfoCardStatusEnum[keyof typeof CardInfoCardStatusEnum];


