/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2026.4.14
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * This array contains the token details.
 */
export interface CardTokensDTO {
    /**
     * This field contains the wallet provider.It can contain two values - googlePay applePay
     */
    'providerType'?: CardTokensDTOProviderTypeEnum;
    /**
     * The reference number for the token provided against the provisioning request.
     */
    'tokenReferenceNumber'?: string;
    /**
     * The token value created for the provisioned card.
     */
    'tokenNumber'?: string;
    /**
     * The identifier for the provisioning service.
     */
    'tokenRequesterId'?: CardTokensDTOTokenRequesterIdEnum;
    /**
     * The unique ID of the device on which the card is provisioned.
     */
    'deviceId'?: string;
    /**
     * The device type in numeric format used for provisioning.
     */
    'deviceType'?: string;
    /**
     * The token status.
     */
    'status'?: CardTokensDTOStatusEnum;
    /**
     * The date and time of token creation in the format - YYYY-MM-DD HH:mm:ss.
     */
    'createdAt'?: string;
    /**
     * The date and time of token update in the format - YYYY-MM-DD HH:mm:ss.
     */
    'updatedAt'?: string;
}

export const CardTokensDTOProviderTypeEnum = {
    GooglePayapplePaysamsungPayunknown: 'googlePay,applePay,samsungPay,unknown',
} as const;

export type CardTokensDTOProviderTypeEnum = typeof CardTokensDTOProviderTypeEnum[keyof typeof CardTokensDTOProviderTypeEnum];
export const CardTokensDTOTokenRequesterIdEnum = {
    GooglePayapplePay: 'googlePay,applePay',
} as const;

export type CardTokensDTOTokenRequesterIdEnum = typeof CardTokensDTOTokenRequesterIdEnum[keyof typeof CardTokensDTOTokenRequesterIdEnum];
export const CardTokensDTOStatusEnum = {
    Activesuspendeddeactivatedunknown: 'ACTIVE,SUSPENDED,DEACTIVATED,UNKNOWN',
} as const;

export type CardTokensDTOStatusEnum = typeof CardTokensDTOStatusEnum[keyof typeof CardTokensDTOStatusEnum];


