/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClientPrefundListResponseDTO
 */
export interface ClientPrefundListResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof ClientPrefundListResponseDTO
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'bankReferenceNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'clientAccountNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'clientCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'clientName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'comments'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'createdBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'currencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'dateOfCreation'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'dateOfTransfer'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'imageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'niumAccountNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'systemReferenceNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'uniquePayerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'uniquePaymentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPrefundListResponseDTO
     */
    'updatedBy'?: string;
}

