/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContainerDTO
 */
export interface ContainerDTO {
    /**
     * This field accepts the client card widget style for container background color.
     * @type {string}
     * @memberof ContainerDTO
     */
    'backgroundColor'?: string;
    /**
     * This field accepts the client card widget style for container border color.
     * @type {string}
     * @memberof ContainerDTO
     */
    'borderColor'?: string;
}

