/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CorporateDocumentUploadBusinessDetailsDTO } from './corporate-document-upload-business-details-dto';

/**
 * 
 * @export
 * @interface CorporateComplianceDocumentRequestDTO
 */
export interface CorporateComplianceDocumentRequestDTO {
    /**
     * 
     * @type {CorporateDocumentUploadBusinessDetailsDTO}
     * @memberof CorporateComplianceDocumentRequestDTO
     */
    'businessDetails'?: CorporateDocumentUploadBusinessDetailsDTO;
    /**
     * This field accepts the regulatory region where the corporation is onboarded.
     * @type {string}
     * @memberof CorporateComplianceDocumentRequestDTO
     */
    'region'?: string;
}

