/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ButtonDTO } from './button-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ContainerDTO } from './container-dto';
// May contain unused imports in some cases
// @ts-ignore
import { InputFieldDTO } from './input-field-dto';

/**
 * 
 * @export
 * @interface CSSAttributeDTO
 */
export interface CSSAttributeDTO {
    /**
     * 
     * @type {ButtonDTO}
     * @memberof CSSAttributeDTO
     */
    'button'?: ButtonDTO;
    /**
     * 
     * @type {ContainerDTO}
     * @memberof CSSAttributeDTO
     */
    'container'?: ContainerDTO;
    /**
     * 
     * @type {InputFieldDTO}
     * @memberof CSSAttributeDTO
     */
    'inputField'?: InputFieldDTO;
}

