/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CSSAttributeDTO } from './cssattribute-dto';

/**
 * 
 * @export
 * @interface CustomerCardWidgetTokenRequestDTO
 */
export interface CustomerCardWidgetTokenRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof CustomerCardWidgetTokenRequestDTO
     */
    'cardType': string;
    /**
     * This field contains the domain name where the widget needs to be embedded
     * @type {string}
     * @memberof CustomerCardWidgetTokenRequestDTO
     */
    'clientDomain'?: string;
    /**
     * 
     * @type {CSSAttributeDTO}
     * @memberof CustomerCardWidgetTokenRequestDTO
     */
    'cssAttributes'?: CSSAttributeDTO;
    /**
     * This field contains the 2-letter [ISO-2 country code](https://nium-documents.s3-eu-west-1.amazonaws.com/spend-documents/Country+Code.pdf) of the destination country.
     * @type {string}
     * @memberof CustomerCardWidgetTokenRequestDTO
     */
    'destinationCountry'?: string;
}

