/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CustomerClientTagRequestDTO } from './customer-client-tag-request-dto';

/**
 * 
 * @export
 * @interface CustomerClientTagsRequestDTO
 */
export interface CustomerClientTagsRequestDTO {
    /**
     * This object accepts the user defined key-value pairs. The maximum number of tags allowed is 15.
     * @type {Array<CustomerClientTagRequestDTO>}
     * @memberof CustomerClientTagsRequestDTO
     */
    'tags': Array<CustomerClientTagRequestDTO>;
}

