/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerTagDTO
 */
export interface CustomerTagDTO {
    /**
     * This field accepts the name of the tag. The maximum key length limit is 128 characters.
     * @type {string}
     * @memberof CustomerTagDTO
     */
    'key'?: string;
    /**
     * This field accepts the value of the tag. The maximum value length limit is 256 characters.
     * @type {string}
     * @memberof CustomerTagDTO
     */
    'value'?: string;
}

