/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ErrorCodes403 } from './error-codes403';

/**
 * error details description
 * @export
 * @interface ErrorDetail403
 */
export interface ErrorDetail403 {
    /**
     * 
     * @type {ErrorCodes403}
     * @memberof ErrorDetail403
     */
    'code'?: ErrorCodes403;
    /**
     * Description of the error.
     * @type {string}
     * @memberof ErrorDetail403
     */
    'description'?: string;
}



