/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2026.4.14
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface FxHoldLockResponseContent {
    /**
     * The audit ID which is generated by Nium as a unique number for internal purposes.
     */
    'audit_id'?: number;
    /**
     * The 3-letter [ISO-4217 source currency code](/docs/currency-and-country-codes) for the source amount.
     */
    'source_currency'?: string;
    /**
     * The 3-letter [ISO-4217 destination currency code](/docs/currency-and-country-codes) for the destination amount.
     */
    'destination_currency'?: string;
    /**
     * The base exchange rate provided by Nium, before any markup is applied.   The legacy API returns the net exchange rate. To derive the base rate, combine this value with `markup_rate`.
     */
    'fx_rate'?: string;
    /**
     * The markup rate charged by Nium.
     */
    'markup_rate'?: string;
    /**
     * The ECB exchange rate.
     */
    'ecb_fx_rate'?: string;
    /**
     * The timestamp until the exchange rate will be valid.  In other words, the timestamp at which the exchange rate held by Nium shall expire. In the `yyyy-MM-ddTHH:mm:ss.SSSZ` format.
     */
    'hold_expiry_at'?: string;
    /**
     * The foreign exchange hold ID.
     */
    'fx_hold_id'?: string;
    /**
     * The status of the given audit ID
     */
    'status'?: string;
    /**
     * The Additional Fx Markup of the given audit ID
     */
    'additionalFxMarkup'?: string;
}

