/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FXStandard404Error
 */
export interface FXStandard404Error {
    /**
     * 
     * @type {string}
     * @memberof FXStandard404Error
     */
    'code'?: FXStandard404ErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof FXStandard404Error
     */
    'description'?: FXStandard404ErrorDescriptionEnum;
}

export const FXStandard404ErrorCodeEnum = {
    ResourceNotFound: 'resource_not_found'
} as const;

export type FXStandard404ErrorCodeEnum = typeof FXStandard404ErrorCodeEnum[keyof typeof FXStandard404ErrorCodeEnum];
export const FXStandard404ErrorDescriptionEnum = {
    ResourceNotFound: 'Resource not found'
} as const;

export type FXStandard404ErrorDescriptionEnum = typeof FXStandard404ErrorDescriptionEnum[keyof typeof FXStandard404ErrorDescriptionEnum];


