/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2026.4.14
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MCCRestrictionDTO {
    /**
     * This array accepts the list of 4-digit mcc codes.
     */
    'merchantCategoryCodes': Array<string>;
    /**
     * The description for enabling or disabling the mcc restriction.
     */
    'description': string;
    /**
     * This field accepts the status and values for this field can be: Active or Inactive. The default value of this field is Active.
     */
    'status'?: MCCRestrictionDTOStatusEnum;
    /**
     * This field accepts the two values: WHITE_LIST BLACK_LIST If this field is not passed then the default value will be WHITE_LIST. If the WHITE_LIST is selected along with the Active status, it means mcc whitelisting is active for the provided list.
     */
    'channelStrategy'?: string;
}

export const MCCRestrictionDTOStatusEnum = {
    Active: 'Active',
    Inactive: 'Inactive',
} as const;

export type MCCRestrictionDTOStatusEnum = typeof MCCRestrictionDTOStatusEnum[keyof typeof MCCRestrictionDTOStatusEnum];


