/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OobCallbackRequestDTO
 */
export interface OobCallbackRequestDTO {
    /**
     * This field represents the unique authorization ID of the transaction received during the OOB authentication.
     * @type {string}
     * @memberof OobCallbackRequestDTO
     */
    'authTransactionId': string;
    /**
     * A reference number is a unique ID associated with the OOB request from your system.
     * @type {string}
     * @memberof OobCallbackRequestDTO
     */
    'referenceNumber': string;
    /**
     * The OOB authentication status code indicated if the transaction is approved or declined. The allowed values are: 001 — OOB authentication approved, 002 — OOB authentication declined.
     * @type {string}
     * @memberof OobCallbackRequestDTO
     */
    'statusCode': OobCallbackRequestDTOStatusCodeEnum;
    /**
     * An optional field to attach a message associated with the authentication.
     * @type {string}
     * @memberof OobCallbackRequestDTO
     */
    'message'?: string;
}

export const OobCallbackRequestDTOStatusCodeEnum = {
    _001002: '001, 002'
} as const;

export type OobCallbackRequestDTOStatusCodeEnum = typeof OobCallbackRequestDTOStatusCodeEnum[keyof typeof OobCallbackRequestDTOStatusCodeEnum];


