/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2026.8.27
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PartialSearchDTO2 {
    /**
     * This field can accept the bank code of specified branch and country.
     */
    'bankCode'?: string;
    /**
     * This field can accept the bank name associated with country.
     */
    'bankName'?: string;
    /**
     * The [2-letter ISO-2 country code](https://nium-documents.s3-eu-west-1.amazonaws.com/spend-documents/Country+Code.pdf) for which routing code search is initiated.
     */
    'countryCode': string;
    /**
     * The [3-letter ISO-4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) for which routing code search is to be initiated.
     */
    'currencyCode'?: string;
    /**
     * This field can accept the different modes of payout. This field can accept one of the following values: LOCAL SWIFT WALLET CARD PROXY(upcoming feature) Default value of the parameter is LOCAL.
     */
    'payoutMethod'?: string;
    /**
     * This field determines the routing code type for the search.
     */
    'routingCodeType': PartialSearchDTO2RoutingCodeTypeEnum;
    /**
     * The partial or full value of the Bank Name on which the search is initiated, for example, it could be DBS.
     */
    'searchValue': string;
}

export const PartialSearchDTO2RoutingCodeTypeEnum = {
    IFSC: 'IFSC',
    SWIFT: 'SWIFT',
    ACH_CODE: 'ACH CODE',
    BSB_CODE: 'BSB CODE',
    SORT_CODE: 'SORT CODE',
    BANK_CODE: 'BANK CODE',
    LOCATION_ID: 'LOCATION ID',
    BRANCH_CODE: 'BRANCH CODE',
    BRANCH_NAME: 'BRANCH NAME',
    TRANSIT_NUMBER: 'TRANSIT NUMBER',
} as const;

export type PartialSearchDTO2RoutingCodeTypeEnum = typeof PartialSearchDTO2RoutingCodeTypeEnum[keyof typeof PartialSearchDTO2RoutingCodeTypeEnum];


