/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PayoutCustomerApiError
 */
export interface PayoutCustomerApiError {
    /**
     * List of errors occurred.
     * @type {Array<string>}
     * @memberof PayoutCustomerApiError
     */
    'errors'?: Array<string>;
    /**
     * Error message descriptor.
     * @type {string}
     * @memberof PayoutCustomerApiError
     */
    'message'?: string;
    /**
     * HttpStatus of the request : BAD_REQUEST, INTERNAL_SERVER_ERROR.
     * @type {string}
     * @memberof PayoutCustomerApiError
     */
    'status'?: PayoutCustomerApiErrorStatusEnum;
}

export const PayoutCustomerApiErrorStatusEnum = {
    _200Ok: '200 OK',
    _400BadRequest: '400 BAD_REQUEST',
    _403Forbidden: '403 FORBIDDEN',
    _404NotFound: '404 NOT_FOUND',
    _500InternalServerError: '500 INTERNAL_SERVER_ERROR',
    _502BadGateway: '502 BAD_GATEWAY',
    _503ServiceUnavailable: '503 SERVICE_UNAVAILABLE'
} as const;

export type PayoutCustomerApiErrorStatusEnum = typeof PayoutCustomerApiErrorStatusEnum[keyof typeof PayoutCustomerApiErrorStatusEnum];


