/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2025.9.9
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductBusinessPartner } from './product-business-partner';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductStakeholderDetails } from './product-stakeholder-details';

/**
 * 
 * @export
 * @interface ProductStakeholders
 */
export interface ProductStakeholders {
    /**
     * 
     * @type {ProductBusinessPartner}
     * @memberof ProductStakeholders
     */
    'businessPartner'?: ProductBusinessPartner;
    /**
     * The universally unique identifier (UUID) for the stakeholder object. If not provided, Nium will generate one automatically. Use the UUID to respond to RFIs or upload supporting documents.
     * @type {string}
     * @memberof ProductStakeholders
     */
    'referenceId'?: string;
    /**
     * 
     * @type {ProductStakeholderDetails}
     * @memberof ProductStakeholders
     */
    'stakeholderDetails'?: ProductStakeholderDetails;
}

