/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2026.4.14
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OnboardingDetails } from './onboarding-details';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductAddresses } from './product-addresses';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductApplicantDetails } from './product-applicant-details';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductAssociationDetails } from './product-association-details';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductBankAccountDetails } from './product-bank-account-details';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductDocumentDetail } from './product-document-detail';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductLegalDetails } from './product-legal-details';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductPartnershipDetails } from './product-partnership-details';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductRegulatoryDetails } from './product-regulatory-details';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductStakeholders } from './product-stakeholders';
// May contain unused imports in some cases
// @ts-ignore
import type { RevenueInfo } from './revenue-info';
// May contain unused imports in some cases
// @ts-ignore
import type { TaxDetails } from './tax-details';

export interface ProductBusinessDetails {
    /**
     * Unique identifier for the `businessDetails` object. If not provided, a system generated one is returned. This ID is used to respond to requests for information (RFIs) or to upload required documents for the business entity.
     */
    'referenceId'?: string;
    /**
     * Registered name of the corporate customer.
     */
    'businessName'?: string;
    /**
     * Registered name of the corporate customer in the local language (e.g., Kanji, Mandarin).
     */
    'businessName_local'?: string;
    /**
     * Official registration number of the corporate customer.
     */
    'businessRegistrationNumber'?: string;
    'searchReferenceId'?: string;
    /**
     * A brief overview of the business. Maximum length: 65,535 characters.
     */
    'description'?: string;
    /**
     * An alternate name the corporate customer uses to conduct business, different from their registered business name.
     */
    'tradeName'?: string;
    /**
     * The full name or business name of the trustee. Applicable only when the customer is a trust.
     */
    'trusteeName'?: string;
    /**
     * The full name or business name of the settlor. Applicable only when the customer is a trust.
     */
    'settlorName'?: string;
    /**
     * A previous name the corporate customer used to conduct business, different from their current registered name.
     */
    'formerName'?: string;
    'partnershipDetails'?: ProductPartnershipDetails;
    'associationDetails'?: ProductAssociationDetails;
    /**
     * The legal entity type of the business (e.g., private company, public company). Use the [Fetch Corporate Constants](/api#tag/customer-account---corporate/get/api/v2/client/{clientHashId}/onboarding/constants) request to retrieve valid values.
     */
    'businessType'?: string;
    'purposeCode'?: string;
    'businessInOtherCountries'?: Array<object>;
    /**
     * The corporate customer’s official website URL.
     */
    'website'?: string;
    /**
     * The stock ticker symbol under which the corporate customer’s shares are traded on a public exchange. Applicable only if the business is publicly listed.
     */
    'stockSymbol'?: boolean;
    'ticker'?: string;
    'legalDetails'?: ProductLegalDetails;
    'regulatoryDetails'?: ProductRegulatoryDetails;
    /**
     * An array of objects containing the individual\'s tax-related information.
     */
    'taxDetails'?: Array<TaxDetails>;
    'addresses'?: ProductAddresses;
    'onboardingDetails'?: OnboardingDetails;
    /**
     * An array of objects containing the businessâ€™s documents and related metadata.
     */
    'documentDetails'?: Array<ProductDocumentDetail>;
    /**
     * An array of stakeholder objects representing individual or business entities associated with the corporate customer, such as directors or ultimate beneficial owners (UBOs).    Each stakeholder can be either a natural person or a legal entity.
     */
    'stakeholders'?: Array<ProductStakeholders>;
    'applicantDetails': ProductApplicantDetails;
    /**
     * Supplementary information about the application. Key-value pairs such as `searchId` and `isSameBusinessAddress` can be included. For more information, see [Corporate Customers](/docs/overview-corporate-customer).
     */
    'additionalInfo'?: { [key: string]: string; };
    /**
     * Indicates if nominee stakeholders—such as directors or shareholders—are included in the onboarding application.
     */
    'hasNominee'?: boolean;
    'revenueInfo'?: RevenueInfo;
    'bankAccountDetails'?: ProductBankAccountDetails;
    /**
     * Indicates if the business is cash-intensive (e.g., casinos, supermarkets, or foreign exchange stores).
     */
    'isCashIntensiveBusiness'?: boolean;
    'isClient'?: boolean;
}

