/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2026.4.14
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ProductBankAccountDetails {
    /**
     * The name of the bank account beneficiary.    - Supports alphanumeric characters and the following special characters: `& . , ( ) _ \' / -.`   - Maximum length: 140 characters.
     */
    'accountName'?: string;
    /**
     * The name of the bank.   Maximum length: 255 characters.
     */
    'bankName'?: string;
    /**
     * Account number. This field can contain alphanumeric characters for a maximum length of 35 characters.
     */
    'accountNumber'?: string;
    /**
     * The primary currency of the bank account.
     */
    'currency'?: string;
    /**
     * Type of Bank account.
     */
    'bankAccountType'?: string;
    /**
     * Routing type of the bank account. Eg. SWIFT, BANK CODE.
     */
    'routingType'?: string;
    /**
     * Routing value of the bank account for the provided routingType. This field can contain alphanumeric characters.
     */
    'routingValue'?: string;
    /**
     * An additional routing type for the bank account (e.g., `BRANCH_CODE`).
     */
    'routingType2'?: string;
    /**
     * The routing value associated with the specified `routingType2`. Supports alphanumeric characters.
     */
    'routingValue2'?: string;
}

