/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2025.9.9
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductAddress } from './product-address';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductContactDetails } from './product-contact-details';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductDocumentDetail } from './product-document-detail';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductProfessionalDetails } from './product-professional-details';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductTaxDetails } from './product-tax-details';

/**
 * 
 * @export
 * @interface ProductStakeholderDetails
 */
export interface ProductStakeholderDetails {
    /**
     * An object that contains additional information about the stakeholder. Details such as isPEP can be sent as Key value pair. Refer to region wise guides for more details.
     * @type {{ [key: string]: string; }}
     * @memberof ProductStakeholderDetails
     */
    'additionalInfo'?: { [key: string]: string; };
    /**
     * 
     * @type {ProductAddress}
     * @memberof ProductStakeholderDetails
     */
    'address'?: ProductAddress;
    /**
     * The country where the individual was born. Use the [Fetch Corporate Constants](/api#tag/customer-account---corporate/get/api/v2/client/{clientHashId}/onboarding/constants) request to retrieve valid values.
     * @type {string}
     * @memberof ProductStakeholderDetails
     */
    'birthCountry'?: string;
    /**
     * 
     * @type {ProductContactDetails}
     * @memberof ProductStakeholderDetails
     */
    'contactDetails'?: ProductContactDetails;
    /**
     * The date of birth of the individual in `yyyy-MM-dd` format.
     * @type {string}
     * @memberof ProductStakeholderDetails
     */
    'dateOfBirth'?: string;
    /**
     * An array that accepts the document details for the stakeholder. This field is required only if documents are being uploaded.
     * @type {Array<ProductDocumentDetail>}
     * @memberof ProductStakeholderDetails
     */
    'documentDetails'?: Array<ProductDocumentDetail>;
    /**
     * The first name of the individual.
     * @type {string}
     * @memberof ProductStakeholderDetails
     */
    'firstName'?: string;
    /**
     * The first name of the individual in the local language e.g. Kanji, Mandarin.
     * @type {string}
     * @memberof ProductStakeholderDetails
     */
    'firstName_local'?: string;
    /**
     * This field accepts the gender of the stakeholder. Available values include:   - Male   - Female
     * @type {string}
     * @memberof ProductStakeholderDetails
     */
    'gender'?: string;
    /**
     * Specifies the KYC verification method for the individual (e.g., `E_KYC`, `MANUAL_KYC`).
     * @type {string}
     * @memberof ProductStakeholderDetails
     */
    'kycMode'?: string;
    /**
     * The last name of the individual.
     * @type {string}
     * @memberof ProductStakeholderDetails
     */
    'lastName'?: string;
    /**
     * The individual\'s last name in the local language e.g. Kanji, Mandarin.
     * @type {string}
     * @memberof ProductStakeholderDetails
     */
    'lastName_local'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductStakeholderDetails
     */
    'liveAuthorizer'?: boolean;
    /**
     * This field contains the middle name of the individual.
     * @type {string}
     * @memberof ProductStakeholderDetails
     */
    'middleName'?: string;
    /**
     * The country of the individual\'s address. Use the [Fetch Corporate Constants](/api#tag/customer-account---corporate/get/api/v2/client/{clientHashId}/onboarding/constants) request to retrieve valid country values.
     * @type {string}
     * @memberof ProductStakeholderDetails
     */
    'nationality'?: string;
    /**
     * The occupation of the individual. Use the [Fetch Corporate Constants](/api#tag/customer-account---corporate/get/api/v2/client/{clientHashId}/onboarding/constants) request to retrieve valid values.
     * @type {string}
     * @memberof ProductStakeholderDetails
     */
    'occupation'?: string;
    /**
     * Accepts the positions held by the individual. Use the [Fetch Corporate Constants](/api#tag/customer-account---corporate/GET/api/v2/client/{clientHashId}/onboarding/constants) request to get a list of valid values.
     * @type {Array<ProductProfessionalDetails>}
     * @memberof ProductStakeholderDetails
     */
    'professionalDetails'?: Array<ProductProfessionalDetails>;
    /**
     * An array of objects containing the individual\'s tax-related information.
     * @type {Array<ProductTaxDetails>}
     * @memberof ProductStakeholderDetails
     */
    'taxDetails'?: Array<ProductTaxDetails>;
}

