/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConversionSchedule } from './conversion-schedule';
// May contain unused imports in some cases
// @ts-ignore
import type { ExecutionType } from './execution-type';
// May contain unused imports in some cases
// @ts-ignore
import type { LockPeriod } from './lock-period';
// May contain unused imports in some cases
// @ts-ignore
import type { QuoteType } from './quote-type';

/**
 * 
 * @export
 * @interface QuoteCreationResponse
 */
export interface QuoteCreationResponse {
    /**
     * Unique identifier of the quote.
     * @type {string}
     * @memberof QuoteCreationResponse
     */
    'id'?: string;
    /**
     * Exchange rate with markup to be used for the conversion.
     * @type {number}
     * @memberof QuoteCreationResponse
     */
    'netExchangeRate'?: number;
    /**
     * Expiry time of the quote in UTC.
     * @type {string}
     * @memberof QuoteCreationResponse
     */
    'expiryTime'?: string;
    /**
     * 3-letter [ISO-4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) for the source amount.
     * @type {string}
     * @memberof QuoteCreationResponse
     */
    'sourceCurrencyCode'?: string;
    /**
     * 3-letter [ISO-4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) for the destination amount.
     * @type {string}
     * @memberof QuoteCreationResponse
     */
    'destinationCurrencyCode'?: string;
    /**
     * 
     * @type {QuoteType}
     * @memberof QuoteCreationResponse
     */
    'quoteType'?: QuoteType;
    /**
     * 
     * @type {ConversionSchedule}
     * @memberof QuoteCreationResponse
     */
    'conversionSchedule'?: ConversionSchedule;
    /**
     * 
     * @type {LockPeriod}
     * @memberof QuoteCreationResponse
     */
    'lockPeriod'?: LockPeriod;
    /**
     * 
     * @type {ExecutionType}
     * @memberof QuoteCreationResponse
     */
    'executionType'?: ExecutionType;
    /**
     * Foreign exchange market rate for the currency pair, used as the benchmark for quote calculation.
     * @type {number}
     * @memberof QuoteCreationResponse
     */
    'exchangeRate'?: number;
    /**
     * Markup rate applied to the exchange rate for the conversion by Nium.
     * @type {number}
     * @memberof QuoteCreationResponse
     */
    'markupRate'?: number;
    /**
     * Markup rate configured at the client level during the initial setup. If a customer level markup is not configured, then the MarkupRate defaults to this ClientMarkupRate.
     * @type {number}
     * @memberof QuoteCreationResponse
     */
    'clientMarkupRate'?: number;
    /**
     * Unique identifier of the customer.
     * @type {string}
     * @memberof QuoteCreationResponse
     */
    'customerHashId'?: string;
    /**
     * Europe Central Bank\'s exchange rate for this currency pair, provided only for EU and UK.
     * @type {number}
     * @memberof QuoteCreationResponse
     */
    'ecbExchangeRate'?: number;
    /**
     * Time in UTC at which exchange rate was obtained from the rate provider
     * @type {string}
     * @memberof QuoteCreationResponse
     */
    'rateCaptureTime'?: string;
    /**
     * The source amount to be converted to the destination currency. This value is for reference only and will not be used as the actual conversion amount.
     * @type {number}
     * @memberof QuoteCreationResponse
     */
    'sourceAmount'?: number;
    /**
     * The amount needed in the destination currency. This value is for reference only and will not be used as the actual conversion amount.
     * @type {number}
     * @memberof QuoteCreationResponse
     */
    'destinationAmount'?: number;
    /**
     * The amount charged in the destination currency as the markup for the conversion.
     * @type {number}
     * @memberof QuoteCreationResponse
     */
    'destinationMarkupAmount'?: number;
    /**
     * Returns <code>true</code> if an FX_MARKUP_OFFMARKET fee has been applied. This field is only returned if off-market requests have been enabled by Nium. For more information, see <a href=\"https://docs.nium.com/apis/docs/fx-overview#off-market-rates\">FX - Overview</a>. 
     * @type {boolean}
     * @memberof QuoteCreationResponse
     */
    'isOffMarket'?: boolean;
    /**
     * Time of creation in UTC.
     * @type {string}
     * @memberof QuoteCreationResponse
     */
    'createdTime'?: string;
}



