/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RemittanceResponseDTO
 */
export interface RemittanceResponseDTO {
    /**
     * This field is estimated delivery time of transaction.
     * @type {string}
     * @memberof RemittanceResponseDTO
     */
    'estimatedDeliveryTime'?: string;
    /**
     * This field will return a success message if the money transferred successfully.
     * @type {string}
     * @memberof RemittanceResponseDTO
     */
    'message'?: string;
    /**
     * This field contains the unique payment ID.
     * @type {string}
     * @memberof RemittanceResponseDTO
     */
    'payment_id'?: string;
    /**
     * This is a unique system reference number assigned to the transaction.
     * @type {string}
     * @memberof RemittanceResponseDTO
     */
    'systemReferenceNumber'?: string;
    /**
     * This is a unique system reference number assigned to the transaction.
     * @type {string}
     * @memberof RemittanceResponseDTO
     */
    'system_reference_number'?: string;
}

