/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Standard401Error
 */
export interface Standard401Error {
    /**
     * 
     * @type {string}
     * @memberof Standard401Error
     */
    'code'?: Standard401ErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof Standard401Error
     */
    'description'?: Standard401ErrorDescriptionEnum;
}

export const Standard401ErrorCodeEnum = {
    Unauthorized: 'unauthorized'
} as const;

export type Standard401ErrorCodeEnum = typeof Standard401ErrorCodeEnum[keyof typeof Standard401ErrorCodeEnum];
export const Standard401ErrorDescriptionEnum = {
    AccessDenied: 'Access Denied'
} as const;

export type Standard401ErrorDescriptionEnum = typeof Standard401ErrorDescriptionEnum[keyof typeof Standard401ErrorDescriptionEnum];


