/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2025.9.9
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * This array contains an object for each card limit parameter. This object contains the below data elements. Please refer the example for exact structure.
 * @export
 * @interface TransactionLimitDTO
 */
export interface TransactionLimitDTO {
    /**
     * This is the 16-digit masked card number in format 1234-56xx-xxxx-3456.
     * @type {string}
     * @memberof TransactionLimitDTO
     */
    'maskedCardNumber'?: string;
    /**
     * This field accepts the limit type to be set. It can take the following values: PER_TRANSACTION_AMOUNT_LIMIT DAILY_AMOUNT_LIMIT MONTHLY_AMOUNT_LIMIT LIFETIME_AMOUNT_LIMIT LIFETIME_COUNT_LIMIT TRANSACTION_DURATION_LIMIT
     * @type {string}
     * @memberof TransactionLimitDTO
     */
    'type': TransactionLimitDTOTypeEnum;
    /**
     * This field accepts the values for each card-level limits. It accepts a date range in the yyyymmdd-yyyymmdd format and UTC +00 time zone as a string when type is TRANSACTION_DURATION_LIMIT. Otherwise, it accepts the limit value.
     * @type {string}
     * @memberof TransactionLimitDTO
     */
    'value': string;
    /**
     * This field contains the threshold percentage which is calculated on the value as a threshold or margin which is to be allowed for authorization when a transaction exceeds the specified limits. The format is Decimal(3,4).
     * @type {number}
     * @memberof TransactionLimitDTO
     */
    'additionalPercentage': number;
    /**
     * This field defines whether a particular limit is active or not. It can accept one of the two values: Active or Inactive.
     * @type {string}
     * @memberof TransactionLimitDTO
     */
    'status': TransactionLimitDTOStatusEnum;
    /**
     * This field contains the timestamp of limit generation.
     * @type {string}
     * @memberof TransactionLimitDTO
     */
    'createdAt'?: string;
    /**
     * This field contains the timestamp of limit updation.
     * @type {string}
     * @memberof TransactionLimitDTO
     */
    'updatedAt'?: string;
}

export const TransactionLimitDTOTypeEnum = {
    PerTransactionAmountLimit: 'PER_TRANSACTION_AMOUNT_LIMIT',
    DailyAmountLimit: 'DAILY_AMOUNT_LIMIT',
    MonthlyAmountLimit: 'MONTHLY_AMOUNT_LIMIT',
    LifetimeAmountLimit: 'LIFETIME_AMOUNT_LIMIT',
    LifetimeCountLimit: 'LIFETIME_COUNT_LIMIT',
    TransactionDurationLimit: 'TRANSACTION_DURATION_LIMIT'
} as const;

export type TransactionLimitDTOTypeEnum = typeof TransactionLimitDTOTypeEnum[keyof typeof TransactionLimitDTOTypeEnum];
export const TransactionLimitDTOStatusEnum = {
    Active: 'Active',
    Inactive: 'Inactive'
} as const;

export type TransactionLimitDTOStatusEnum = typeof TransactionLimitDTOStatusEnum[keyof typeof TransactionLimitDTOStatusEnum];


