/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TransactionClientTagResponseDTO } from './transaction-client-tag-response-dto';

/**
 * 
 * @export
 * @interface TransactionClientTagsResponseDTO
 */
export interface TransactionClientTagsResponseDTO {
    /**
     * 
     * @type {Array<TransactionClientTagResponseDTO>}
     * @memberof TransactionClientTagsResponseDTO
     */
    'tags'?: Array<TransactionClientTagResponseDTO>;
}

