/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TransactionsBusinessDTO
 */
export interface TransactionsBusinessDTO {
    /**
     * Mark or unmark a transactions as a business transactions.
     * @type {boolean}
     * @memberof TransactionsBusinessDTO
     */
    'businessTransaction': boolean;
}

