/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TransactionClientTagRequestDTO } from './transaction-client-tag-request-dto';

/**
 * 
 * @export
 * @interface TransactionClientTagsRequestDTO
 */
export interface TransactionClientTagsRequestDTO {
    /**
     * This object accepts the user defined key-value pairs. The maximum number of tags allowed is 15.
     * @type {Array<TransactionClientTagRequestDTO>}
     * @memberof TransactionClientTagsRequestDTO
     */
    'tags': Array<TransactionClientTagRequestDTO>;
}

