/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateCustomerDTO
 */
export interface UpdateCustomerDTO {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof UpdateCustomerDTO
     */
    'additionalInfo'?: { [key: string]: string; };
    /**
     * This field accepts the authentication code generated as part of SCA (Strong Customer Authentication). Note: : Authentication code must be passed if regulatory region of the program is UK or EU. This field does not accept a value for any other region.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'authenticationCode'?: string;
    /**
     * Billing address line one of a customer.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'billingAddress1'?: string;
    /**
     * Billing address line two of a customer.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'billingAddress2'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'billingAddressId'?: string;
    /**
     * Billing address city name.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'billingCity'?: string;
    /**
     * This field accepts the 2-letter [ISO Alpha-2 country code](doc:currency-and-country-codes) denoting the country of customer’s billing address. It is important to pass this field if the card to be issued is to be used for GooglePay or ApplePay provisioning.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'billingCountry'?: string;
    /**
     * Billing landmark address field.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'billingLandmark'?: string;
    /**
     * Billing address state name.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'billingState'?: string;
    /**
     * Billing address ZIP code.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'billingZipCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'blockType'?: string;
    /**
     * Line one of the customer\'s correspondence address.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'correspondenceAddress1'?: string;
    /**
     * Line two of the customer\'s correspondence address.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'correspondenceAddress2'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'correspondenceAddressId'?: string;
    /**
     * Correspondence address city name.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'correspondenceCity'?: string;
    /**
     * This field accepts the 2-letter [ISO Alpha-2 country code](doc:currency-and-country-codes) denoting the country of customer’s correspondence address.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'correspondenceCountry'?: string;
    /**
     * Correspondence landmark address field.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'correspondenceLandmark'?: string;
    /**
     * Correspondence address state name.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'correspondenceState'?: string;
    /**
     * Correspondence postal/ZIP code of a customer.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'correspondenceZipCode'?: string;
    /**
     * This field contains the 2-letter [ISO Alpha-2 country code](doc:currency-and-country-codes) for identifying the country prefix to a mobile number.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'countryCode'?: string;
    /**
     * The country IP for the device by the customer for initiating the request.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'countryIP'?: string;
    /**
     * Unique customer identifier generated on customer creation.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'customerHashId'?: string;
    /**
     * Line one of the address where the customer would like to receive a card.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'deliveryAddress1'?: string;
    /**
     * Line two of the customer\'s delivery address.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'deliveryAddress2'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'deliveryAddressId'?: string;
    /**
     * Customer\'s city name.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'deliveryCity'?: string;
    /**
     * This field accepts the 2-letter [ISO Alpha-2 country code](doc:currency-and-country-codes) denoting the country of customer\'s delivery address.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'deliveryCountry'?: string;
    /**
     * delivery landmark address field.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'deliveryLandmark'?: string;
    /**
     * Customer\'s state name.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'deliveryState'?: string;
    /**
     * Customer\'s ZIP code.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'deliveryZipCode'?: string;
    /**
     * The OS of the device used by the customer for initiating the request.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'deviceInfo'?: string;
    /**
     * Customer\'s email address
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'email'?: string;
    /**
     * This field accepts the employee Id for the customer, in case of a corporate program.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'employeeId'?: string;
    /**
     * The IP address of the device used by the customer for initiating the request.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'ipAddress'?: string;
    /**
     * Mobile number to be updated.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'mobile'?: string;
    /**
     * This field contains the customer\'s name in native language. Maximum character limit: 40
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'nativeLanguageName'?: string;
    /**
     * This is the fee segment associated with a client. Maximum character limit: 64
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'segment'?: string;
    /**
     * The session Id for the session of the customer for initiating the request.
     * @type {string}
     * @memberof UpdateCustomerDTO
     */
    'sessionId'?: string;
}

