/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WalletPaymentIdsResponseDTO } from './wallet-payment-ids-response-dto';

/**
 * 
 * @export
 * @interface VirtualAccountResponseDTO
 */
export interface VirtualAccountResponseDTO {
    /**
     * 
     * @type {Array<WalletPaymentIdsResponseDTO>}
     * @memberof VirtualAccountResponseDTO
     */
    'content'?: Array<WalletPaymentIdsResponseDTO>;
    /**
     * Details the total number of items retunred in the response.
     * @type {number}
     * @memberof VirtualAccountResponseDTO
     */
    'totalElements'?: number;
    /**
     * Details the number of pages in the response body.
     * @type {number}
     * @memberof VirtualAccountResponseDTO
     */
    'totalPages'?: number;
}

