/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WalletWalletRfiAttributeResponse } from './wallet-wallet-rfi-attribute-response';

/**
 * 
 * @export
 * @interface WalletTransactionRfiDetailsResponse
 */
export interface WalletTransactionRfiDetailsResponse {
    /**
     * The description of the RFI.
     * @type {string}
     * @memberof WalletTransactionRfiDetailsResponse
     */
    'description'?: string;
    /**
     * The type of the document if applicable, for example, POI, POA, etc.
     * @type {string}
     * @memberof WalletTransactionRfiDetailsResponse
     */
    'documentType'?: string;
    /**
     * Details if the RFI is required or not.
     * @type {boolean}
     * @memberof WalletTransactionRfiDetailsResponse
     */
    'mandatory'?: boolean;
    /**
     * The remarks that were provided while raising the RFI.
     * @type {string}
     * @memberof WalletTransactionRfiDetailsResponse
     */
    'remarks'?: string;
    /**
     * An array that contains the required data for the RFI.
     * @type {Array<WalletWalletRfiAttributeResponse>}
     * @memberof WalletTransactionRfiDetailsResponse
     */
    'requiredData'?: Array<WalletWalletRfiAttributeResponse>;
    /**
     * The unique RFI hash ID.
     * @type {string}
     * @memberof WalletTransactionRfiDetailsResponse
     */
    'rfiHashId'?: string;
    /**
     * The unique identifier for the group of RFI raised for the customer transaction.
     * @type {string}
     * @memberof WalletTransactionRfiDetailsResponse
     */
    'rfiId'?: string;
    /**
     * The transaction RFI status.
     * @type {string}
     * @memberof WalletTransactionRfiDetailsResponse
     */
    'rfiStatus'?: WalletTransactionRfiDetailsResponseRfiStatusEnum;
    /**
     * The type of transaction entity. Available values include: DEBTOR CREDITOR
     * @type {string}
     * @memberof WalletTransactionRfiDetailsResponse
     */
    'transactionEntityType'?: WalletTransactionRfiDetailsResponseTransactionEntityTypeEnum;
    /**
     * The type of RFI. Available values include document or data.
     * @type {string}
     * @memberof WalletTransactionRfiDetailsResponse
     */
    'type'?: string;
}

export const WalletTransactionRfiDetailsResponseRfiStatusEnum = {
    None: 'NONE',
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED',
    ActionRequired: 'ACTION_REQUIRED',
    Error: 'ERROR',
    Reject: 'REJECT',
    Expired: 'EXPIRED',
    RfiRequested: 'RFI_REQUESTED',
    RfiResponded: 'RFI_RESPONDED',
    Unknown: 'UNKNOWN',
    Initiated: 'INITIATED',
    Pending: 'PENDING',
    Clear: 'CLEAR',
    Closed: 'CLOSED'
} as const;

export type WalletTransactionRfiDetailsResponseRfiStatusEnum = typeof WalletTransactionRfiDetailsResponseRfiStatusEnum[keyof typeof WalletTransactionRfiDetailsResponseRfiStatusEnum];
export const WalletTransactionRfiDetailsResponseTransactionEntityTypeEnum = {
    Debtor: 'DEBTOR',
    Creditor: 'CREDITOR'
} as const;

export type WalletTransactionRfiDetailsResponseTransactionEntityTypeEnum = typeof WalletTransactionRfiDetailsResponseTransactionEntityTypeEnum[keyof typeof WalletTransactionRfiDetailsResponseTransactionEntityTypeEnum];


