/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WalletFundResponseDTOPaymentMethodsInner } from './wallet-fund-response-dtopayment-methods-inner';

/**
 * 
 * @export
 * @interface WalletFundResponseDTO
 */
export interface WalletFundResponseDTO {
    /**
     * The credited amount.
     * @type {number}
     * @memberof WalletFundResponseDTO
     */
    'destinationAmount'?: number;
    /**
     * This field contains the 3-letter [ISO-4217 currency code](doc:currency-and-country-codes) for the destination amount.
     * @type {string}
     * @memberof WalletFundResponseDTO
     */
    'destinationCurrencyCode'?: string;
    /**
     * It is an array composed of three types of objects:  1. Bank transfer data 2. Dynamic pay now code 3. Static pay now code 
     * @type {Array<WalletFundResponseDTOPaymentMethodsInner>}
     * @memberof WalletFundResponseDTO
     */
    'paymentMethods'?: Array<WalletFundResponseDTOPaymentMethodsInner>;
    /**
     * This is 3DS stripe URL generated for entering OTP.
     * @type {string}
     * @memberof WalletFundResponseDTO
     */
    'returnUrl'?: string;
    /**
     * An amount to be converted.
     * @type {number}
     * @memberof WalletFundResponseDTO
     */
    'sourceAmount'?: number;
    /**
     * This field contains the 3-letter [ISO-4217 currency code](doc:currency-and-country-codes) for the source amount.
     * @type {string}
     * @memberof WalletFundResponseDTO
     */
    'sourceCurrencyCode'?: string;
    /**
     * This field can take the following values:  Pending: Transaction authorization is awaiting success or failure Approved: Transaction is successfully authorized Rejected: Transaction is rejected due to NIUM risk and compliance policies Declined: Transaction is declined Reversal: Transaction is reversed Disputed: A dispute has been raised for the transaction DisputeClosed: Dispute raised for the transaction is resolved.
     * @type {string}
     * @memberof WalletFundResponseDTO
     */
    'status'?: string;
    /**
     * Transaction reference number generated by card issuance platform.
     * @type {string}
     * @memberof WalletFundResponseDTO
     */
    'systemReferenceNumber'?: string;
}

