/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2024.8.20
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WithSourceAmount
 */
export interface WithSourceAmount {
    /**
     * The source amount to be converted to the destination currency. This value is for reference only and will not be used as the actual conversion amount.
     * @type {number}
     * @memberof WithSourceAmount
     */
    'sourceAmount'?: number;
}

