/**
 * NIUM Platform
 * NIUM Platform
 *
 * OpenAPI spec version: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ActivateCardRequestV2DTO {
    /**
    * This field can be used to send the activation code.
    */
    'activationCode': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "activationCode",
            "baseName": "activationCode",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ActivateCardRequestV2DTO.attributeTypeMap;
    }

    public constructor() {
    }
}

