/**
 * NIUM Platform
 * NIUM Platform
 *
 * OpenAPI spec version: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BalanceAmount } from '../models/BalanceAmount';
import { HttpFile } from '../http/http';

export class Balance {
    'balanceAmount'?: BalanceAmount;
    'balanceType'?: string;
    /**
    * Basic Bank Account Number (BBAN) Identifier.
    */
    'bban'?: string;
    /**
    * This field contains the 3-letter [ISO-4217 currency code](doc:currency-and-country-codes).
    */
    'currency'?: string;
    /**
    * International Bank Account Number (IBAN) of an account balance, for example: \"FR7612345987650123456789014\".
    */
    'iban'?: string;
    /**
    * Primary Account Number (PAN) of a card in a masked form. This is used for card account in responses, for example \" 1234\". The maximum length: 35
    */
    'maskedPan'?: string;
    /**
    * An alias to access a payment account via a registered mobile phone number. The maximum length: 35
    */
    'msisdn'?: string;
    /**
    * Primary Account Number (PAN) of a card, can be tokenized by the ASPSP due to PCI DSS requirements. This is used for card account in responses. The maximum length: 35
    */
    'pan'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "balanceAmount",
            "baseName": "balanceAmount",
            "type": "BalanceAmount",
            "format": ""
        },
        {
            "name": "balanceType",
            "baseName": "balanceType",
            "type": "string",
            "format": ""
        },
        {
            "name": "bban",
            "baseName": "bban",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "iban",
            "baseName": "iban",
            "type": "string",
            "format": ""
        },
        {
            "name": "maskedPan",
            "baseName": "maskedPan",
            "type": "string",
            "format": ""
        },
        {
            "name": "msisdn",
            "baseName": "msisdn",
            "type": "string",
            "format": ""
        },
        {
            "name": "pan",
            "baseName": "pan",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Balance.attributeTypeMap;
    }

    public constructor() {
    }
}

