/**
 * NIUM Platform
 * NIUM Platform
 *
 * OpenAPI spec version: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Card block/replace status
*/
export class BlockAndReplaceStatus {
    /**
    * This field contains the card block reason.
    */
    'blockReason'?: string;
    /**
    * This field contains the card replacement date
    */
    'replacedOn'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "blockReason",
            "baseName": "blockReason",
            "type": "string",
            "format": ""
        },
        {
            "name": "replacedOn",
            "baseName": "replacedOn",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BlockAndReplaceStatus.attributeTypeMap;
    }

    public constructor() {
    }
}

