/**
 * NIUM Platform
 * NIUM Platform
 *
 * OpenAPI spec version: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AddressV2 } from '../models/AddressV2';
import { BusinessPartnerLegalDetails } from '../models/BusinessPartnerLegalDetails';
import { HttpFile } from '../http/http';

export class BusinessPartnerV2 {
    'businessEntityType'?: string;
    'businessName'?: string;
    'businessRegistrationNumber'?: string;
    /**
    * This field contains the legal entity type of the business.
    */
    'businessType'?: string;
    'legalDetails'?: BusinessPartnerLegalDetails;
    'registeredAddress'?: AddressV2;
    'sharePercentage'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "businessEntityType",
            "baseName": "businessEntityType",
            "type": "string",
            "format": ""
        },
        {
            "name": "businessName",
            "baseName": "businessName",
            "type": "string",
            "format": ""
        },
        {
            "name": "businessRegistrationNumber",
            "baseName": "businessRegistrationNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "businessType",
            "baseName": "businessType",
            "type": "string",
            "format": ""
        },
        {
            "name": "legalDetails",
            "baseName": "legalDetails",
            "type": "BusinessPartnerLegalDetails",
            "format": ""
        },
        {
            "name": "registeredAddress",
            "baseName": "registeredAddress",
            "type": "AddressV2",
            "format": ""
        },
        {
            "name": "sharePercentage",
            "baseName": "sharePercentage",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BusinessPartnerV2.attributeTypeMap;
    }

    public constructor() {
    }
}

