/**
 * NIUM Platform
 * NIUM Platform
 *
 * OpenAPI spec version: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Reason for a conversion cancellation.    * `user_cancel`: User initiated cancellation.   * `insufficient_fund`: Cancellation due to insufficient balance in the wallet at the time of conversion execution. 
*/
export enum CancellationReason {
    UserCancel = 'user_cancel',
    InsufficientFund = 'insufficient_fund'
}
