/**
 * NIUM Platform
 * NIUM Platform
 *
 * OpenAPI spec version: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransactionResponseDTO } from '../models/TransactionResponseDTO';
import { HttpFile } from '../http/http';

export class ClientTransactionsResponseDTO {
    /**
    * This field contains an array that holds additional data.
    */
    'content'?: Array<TransactionResponseDTO>;
    /**
    * This field contains the number of elements in the response body.
    */
    'totalElements'?: number;
    /**
    * This field contains the number of pages in response body.
    */
    'totalPages'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "Array<TransactionResponseDTO>",
            "format": ""
        },
        {
            "name": "totalElements",
            "baseName": "totalElements",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalPages",
            "baseName": "totalPages",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return ClientTransactionsResponseDTO.attributeTypeMap;
    }

    public constructor() {
    }
}

