/**
 * NIUM Platform
 * NIUM Platform
 *
 * OpenAPI spec version: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IdentificationDocumentDTO } from '../models/IdentificationDocumentDTO';
import { HttpFile } from '../http/http';

export class ComplianceIdentificationDocDTO {
    /**
    * This field accepts the color of the medicare card which may be one of three values - G, B, Y. It is mandatory for medicare card.
    */
    'identificationDocColor'?: string;
    /**
    * This field accepts the identification document expiry date. The valid values are: dateOfExpiry for passport dateOfExpiry for government letter 
    */
    'identificationDocExpiry'?: string;
    /**
    * This field accepts the name of the document holder exactly according to the proof of identity document uploaded.
    */
    'identificationDocHolderName'?: string;
    /**
    * This field accepts the country of the issuance for the document being uploaded.
    */
    'identificationDocIssuanceCountry'?: string;
    /**
    * This field is mandatory for medicare card and accepts the document reference number for the following documents: Government Letter Bank Statement Utility Bill Employer Letter Medicare Card
    */
    'identificationDocReferenceNumber'?: string;
    /**
    * This is an array of actual Base-64 documents as required. The maximum allowed size of this payload is 10MB. A separate object is needed for each document image.
    */
    'identificationDocument'?: Array<IdentificationDocumentDTO>;
    /**
    * This field accepts the authorized issuer of the document for example, the name of the government agency issuing the document.
    */
    'identificationIssuingAuthority'?: string;
    /**
    * This field accepts the identification issuing date. The valid values are: dateOfIssue for FIN dateOfIssue for passport dateOfIssue for GovernmentLetter statementGeneratedOn for BankStatement billGeneratedOn for utilityBill
    */
    'identificationIssuingDate'?: string;
    /**
    * This field accepts the identificationType for the document being uploaded for KYC. Some commonly used values are as follows: Selfie Passport Government Id NRIC FIN Driving Licence Government Letter Bank Statement Utility Bill Employer Letter Note: For EU, the acceptable values for identificationType are Passport, National ID.
    */
    'identificationType': string;
    /**
    * This field accepts the identification value. The valid values for identificationValue are: For NRIC/FIN/Passport: Unique NRIC/FIN/passport number. For GovernmentID: Unique Id number as per the document. For selfieWithId/GovernmentLetter: Blank For others(as proof of address): Unique number as per document or blank(can pass the value in identificationDocReferenceNumber)
    */
    'identificationValue'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "identificationDocColor",
            "baseName": "identificationDocColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "identificationDocExpiry",
            "baseName": "identificationDocExpiry",
            "type": "string",
            "format": ""
        },
        {
            "name": "identificationDocHolderName",
            "baseName": "identificationDocHolderName",
            "type": "string",
            "format": ""
        },
        {
            "name": "identificationDocIssuanceCountry",
            "baseName": "identificationDocIssuanceCountry",
            "type": "string",
            "format": ""
        },
        {
            "name": "identificationDocReferenceNumber",
            "baseName": "identificationDocReferenceNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "identificationDocument",
            "baseName": "identificationDocument",
            "type": "Array<IdentificationDocumentDTO>",
            "format": ""
        },
        {
            "name": "identificationIssuingAuthority",
            "baseName": "identificationIssuingAuthority",
            "type": "string",
            "format": ""
        },
        {
            "name": "identificationIssuingDate",
            "baseName": "identificationIssuingDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "identificationType",
            "baseName": "identificationType",
            "type": "string",
            "format": ""
        },
        {
            "name": "identificationValue",
            "baseName": "identificationValue",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ComplianceIdentificationDocDTO.attributeTypeMap;
    }

    public constructor() {
    }
}

