/**
 * NIUM Platform
 * NIUM Platform
 *
 * OpenAPI spec version: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* This object accepts the legal details of the corporate entity being onboarded.  AU: Required EU: Required UK: Required SG: Required
*/
export class CorporateLegalDetails {
    /**
    * This field accepts the 2-letter [ISO Alpha-2 country code](doc:currency-and-country-codes) for the country.  AU: Required EU: Required UK: Required SG: Required
    */
    'registeredCountry'?: string;
    /**
    * This field accepts the business registration date for the new corporate entity to be onboarded.  AU: Required EU: Required UK: Required SG: Required
    */
    'registeredDate'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "registeredCountry",
            "baseName": "registeredCountry",
            "type": "string",
            "format": ""
        },
        {
            "name": "registeredDate",
            "baseName": "registeredDate",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CorporateLegalDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

