/**
 * NIUM Platform
 * NIUM Platform
 *
 * OpenAPI spec version: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TypedErrorErrorCodes } from '../models/TypedErrorErrorCodes';
import { HttpFile } from '../http/http';

export class NewErrorResponse {
    'errors'?: Array<TypedErrorErrorCodes>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<TypedErrorErrorCodes>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NewErrorResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

