/**
 * NIUM Platform
 * NIUM Platform
 *
 * OpenAPI spec version: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentIdClientTagResponseDTO } from '../models/PaymentIdClientTagResponseDTO';
import { HttpFile } from '../http/http';

export class PaymentIdCientTagsResponseDTO {
    'tags'?: Array<PaymentIdClientTagResponseDTO>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<PaymentIdClientTagResponseDTO>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentIdCientTagsResponseDTO.attributeTypeMap;
    }

    public constructor() {
    }
}

