/* tslint:disable */
/* eslint-disable */
/**
 * NIUM Platform
 * NIUM Platform
 *
 * The version of the OpenAPI document: 2023.12.12
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { ClientTransactionsResponseDTO } from '../model';
// @ts-ignore
import { WalletApiError } from '../model';
/**
 * ClientTransactionsApi - axios parameter creator
 * @export
 */
export const ClientTransactionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This API allows you to fetch transaction details at the client level.
         * @summary Client Transactions
         * @param {string} clientHashId Unique client identifier generated and shared before API handshake. &gt;ℹ️ INFO  &gt;Query parameters are optional. If query parameters are not passed then by default three months transactions will be returned.
         * @param {string} [authCode] This parameter can be used to filter the transactions based on the authorization code. In case of fund wallet transactions you can provide the systemReferenceNumber as value.
         * @param {string} [authCurrency] This parameter can filter the transactions based on auth currency and accepts 3-letter [ISO-4217 transaction currency code](https://docs.nium.com/apis/docs/currency-and-country-codes).
         * @param {boolean} [businessTransaction] This parameter can filter the transactions based on businessTransaction flag.
         * @param {string} [cardHashId] This field can apply the filter based on the unique card identifier generated during new/add-on card issuance.
         * @param {string} [childCustomerHashId] This field contains the unique child customer identifier generated when new child customer created.
         * @param {string} [customerHashId] Unique identifier generated with customer creation.
         * @param {string} [endDate] End date for fetching the transaction details. The format for endDate is YYYY-MM-DD.
         * @param {string} [mcc] This parameter can filter the transactions based on 4-digit Merchant Category Codes.
         * @param {string} [merchantCategories] This parameter describes the merchant\&#39;s type of business product or service, also known as the Merchant Category Code (MCC) such as Airlines, Restaurants etc.
         * @param {string} [merchantCity] This parameter can filter the transactions based on the merchant city field.
         * @param {string} [merchantCountries] This parameter can filter the transactions based on comma-separated list of 2-letter ISO merchant countries.
         * @param {string} [merchantCountry] This parameter can filter the transactions based on the merchant country field.
         * @param {string} [merchantName] This parameter can filter the transactions based on the merchant name field.
         * @param {ClientTransactionsOrderEnum} [order] The sort order for the results.
         * @param {number} [page] This API may have lot of data in response and supports pagination. Entire response data is divided into pages with size as the upper limit on the number of data. Integer values from 0 onwards are acceptable. Default page is 0.
         * @param {string} [paymentInstrumentHashId] This parameter can filter the transactions based on comma-separated paymentInstrumentHashId.
         * @param {string} [property] The field indicates the response parameter used to sort paginated data, with \&#39;createdAt\&#39; as the default parameter.
         * @param {string} [settlementDate] This parameter can filter the transactions based on the settlement date of the transaction in format yyyyMMdd.
         * @param {string} [settlementStatus] This parameter can filter the transactions based on settlement status. The detailed list of possible values is available in the response of this API.
         * @param {number} [size] This will decide the number of elements per page. Typical values can be 1-20.
         * @param {string} [startDate] From date for fetching the transaction details. The format for startDate is YYYY-MM-DD.
         * @param {ClientTransactionsStatusEnum} [status] This parameter can filter the transactions based on status. The detailed list of possible values is available in the response of this API.
         * @param {string} [systemTraceAuditNumber] This parameter can filter the transactions based on systemTraceAuditNumber.
         * @param {string} [tagKey] This parameter can filter the transactions, based on the exact value of tagKey defined against transactions. This can be used as an independent search parameter.
         * @param {string} [tagValue] This parameter can filter the transactions, based on the approximating value of tagValue(that may be mapped for a tagKey defined against transactions). This can be used as an independent search parameter.
         * @param {string} [transactionCurrency] This field contains the 3-letter [ISO-4217 transaction currency code](https://www.iso.org/iso-4217-currency-codes.html).
         * @param {string} [transactionType] This field contains the transaction can be one of the complete list of transactions mentioned in [Glossary of Transaction Types](https://docs.nium.com/baas/get-transactions#glossary-of-transaction-types).
         * @param {string} [transactionsLabelsKey] This parameter can filter the transactions based on transactionsLabelsKey.
         * @param {string} [transactionsLabelsValue] This parameter can filter the transactions based on transactionsLabelsValue.
         * @param {string} [walletHashId] Unique wallet identifier generated simultaneously with customer creation.
         * @param {string} [xRequestId] Enter a unique UUID value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        clientTransactions: async (clientHashId: string, authCode?: string, authCurrency?: string, businessTransaction?: boolean, cardHashId?: string, childCustomerHashId?: string, customerHashId?: string, endDate?: string, mcc?: string, merchantCategories?: string, merchantCity?: string, merchantCountries?: string, merchantCountry?: string, merchantName?: string, order?: ClientTransactionsOrderEnum, page?: number, paymentInstrumentHashId?: string, property?: string, settlementDate?: string, settlementStatus?: string, size?: number, startDate?: string, status?: ClientTransactionsStatusEnum, systemTraceAuditNumber?: string, tagKey?: string, tagValue?: string, transactionCurrency?: string, transactionType?: string, transactionsLabelsKey?: string, transactionsLabelsValue?: string, walletHashId?: string, xRequestId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientHashId' is not null or undefined
            assertParamExists('clientTransactions', 'clientHashId', clientHashId)
            const localVarPath = `/api/v1/client/{clientHashId}/transactions`
                .replace(`{${"clientHashId"}}`, encodeURIComponent(String(clientHashId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication default required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            if (authCode !== undefined) {
                localVarQueryParameter['authCode'] = authCode;
            }

            if (authCurrency !== undefined) {
                localVarQueryParameter['authCurrency'] = authCurrency;
            }

            if (businessTransaction !== undefined) {
                localVarQueryParameter['businessTransaction'] = businessTransaction;
            }

            if (cardHashId !== undefined) {
                localVarQueryParameter['cardHashId'] = cardHashId;
            }

            if (childCustomerHashId !== undefined) {
                localVarQueryParameter['childCustomerHashId'] = childCustomerHashId;
            }

            if (customerHashId !== undefined) {
                localVarQueryParameter['customerHashId'] = customerHashId;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = endDate;
            }

            if (mcc !== undefined) {
                localVarQueryParameter['mcc'] = mcc;
            }

            if (merchantCategories !== undefined) {
                localVarQueryParameter['merchantCategories'] = merchantCategories;
            }

            if (merchantCity !== undefined) {
                localVarQueryParameter['merchantCity'] = merchantCity;
            }

            if (merchantCountries !== undefined) {
                localVarQueryParameter['merchantCountries'] = merchantCountries;
            }

            if (merchantCountry !== undefined) {
                localVarQueryParameter['merchantCountry'] = merchantCountry;
            }

            if (merchantName !== undefined) {
                localVarQueryParameter['merchantName'] = merchantName;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (paymentInstrumentHashId !== undefined) {
                localVarQueryParameter['paymentInstrumentHashId'] = paymentInstrumentHashId;
            }

            if (property !== undefined) {
                localVarQueryParameter['property'] = property;
            }

            if (settlementDate !== undefined) {
                localVarQueryParameter['settlementDate'] = settlementDate;
            }

            if (settlementStatus !== undefined) {
                localVarQueryParameter['settlementStatus'] = settlementStatus;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = startDate;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (systemTraceAuditNumber !== undefined) {
                localVarQueryParameter['systemTraceAuditNumber'] = systemTraceAuditNumber;
            }

            if (tagKey !== undefined) {
                localVarQueryParameter['tagKey'] = tagKey;
            }

            if (tagValue !== undefined) {
                localVarQueryParameter['tagValue'] = tagValue;
            }

            if (transactionCurrency !== undefined) {
                localVarQueryParameter['transactionCurrency'] = transactionCurrency;
            }

            if (transactionType !== undefined) {
                localVarQueryParameter['transactionType'] = transactionType;
            }

            if (transactionsLabelsKey !== undefined) {
                localVarQueryParameter['transactionsLabelsKey'] = transactionsLabelsKey;
            }

            if (transactionsLabelsValue !== undefined) {
                localVarQueryParameter['transactionsLabelsValue'] = transactionsLabelsValue;
            }

            if (walletHashId !== undefined) {
                localVarQueryParameter['walletHashId'] = walletHashId;
            }

            if (xRequestId != null) {
                localVarHeaderParameter['x-request-id'] = String(xRequestId);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ClientTransactionsApi - functional programming interface
 * @export
 */
export const ClientTransactionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ClientTransactionsApiAxiosParamCreator(configuration)
    return {
        /**
         * This API allows you to fetch transaction details at the client level.
         * @summary Client Transactions
         * @param {string} clientHashId Unique client identifier generated and shared before API handshake. &gt;ℹ️ INFO  &gt;Query parameters are optional. If query parameters are not passed then by default three months transactions will be returned.
         * @param {string} [authCode] This parameter can be used to filter the transactions based on the authorization code. In case of fund wallet transactions you can provide the systemReferenceNumber as value.
         * @param {string} [authCurrency] This parameter can filter the transactions based on auth currency and accepts 3-letter [ISO-4217 transaction currency code](https://docs.nium.com/apis/docs/currency-and-country-codes).
         * @param {boolean} [businessTransaction] This parameter can filter the transactions based on businessTransaction flag.
         * @param {string} [cardHashId] This field can apply the filter based on the unique card identifier generated during new/add-on card issuance.
         * @param {string} [childCustomerHashId] This field contains the unique child customer identifier generated when new child customer created.
         * @param {string} [customerHashId] Unique identifier generated with customer creation.
         * @param {string} [endDate] End date for fetching the transaction details. The format for endDate is YYYY-MM-DD.
         * @param {string} [mcc] This parameter can filter the transactions based on 4-digit Merchant Category Codes.
         * @param {string} [merchantCategories] This parameter describes the merchant\&#39;s type of business product or service, also known as the Merchant Category Code (MCC) such as Airlines, Restaurants etc.
         * @param {string} [merchantCity] This parameter can filter the transactions based on the merchant city field.
         * @param {string} [merchantCountries] This parameter can filter the transactions based on comma-separated list of 2-letter ISO merchant countries.
         * @param {string} [merchantCountry] This parameter can filter the transactions based on the merchant country field.
         * @param {string} [merchantName] This parameter can filter the transactions based on the merchant name field.
         * @param {ClientTransactionsOrderEnum} [order] The sort order for the results.
         * @param {number} [page] This API may have lot of data in response and supports pagination. Entire response data is divided into pages with size as the upper limit on the number of data. Integer values from 0 onwards are acceptable. Default page is 0.
         * @param {string} [paymentInstrumentHashId] This parameter can filter the transactions based on comma-separated paymentInstrumentHashId.
         * @param {string} [property] The field indicates the response parameter used to sort paginated data, with \&#39;createdAt\&#39; as the default parameter.
         * @param {string} [settlementDate] This parameter can filter the transactions based on the settlement date of the transaction in format yyyyMMdd.
         * @param {string} [settlementStatus] This parameter can filter the transactions based on settlement status. The detailed list of possible values is available in the response of this API.
         * @param {number} [size] This will decide the number of elements per page. Typical values can be 1-20.
         * @param {string} [startDate] From date for fetching the transaction details. The format for startDate is YYYY-MM-DD.
         * @param {ClientTransactionsStatusEnum} [status] This parameter can filter the transactions based on status. The detailed list of possible values is available in the response of this API.
         * @param {string} [systemTraceAuditNumber] This parameter can filter the transactions based on systemTraceAuditNumber.
         * @param {string} [tagKey] This parameter can filter the transactions, based on the exact value of tagKey defined against transactions. This can be used as an independent search parameter.
         * @param {string} [tagValue] This parameter can filter the transactions, based on the approximating value of tagValue(that may be mapped for a tagKey defined against transactions). This can be used as an independent search parameter.
         * @param {string} [transactionCurrency] This field contains the 3-letter [ISO-4217 transaction currency code](https://www.iso.org/iso-4217-currency-codes.html).
         * @param {string} [transactionType] This field contains the transaction can be one of the complete list of transactions mentioned in [Glossary of Transaction Types](https://docs.nium.com/baas/get-transactions#glossary-of-transaction-types).
         * @param {string} [transactionsLabelsKey] This parameter can filter the transactions based on transactionsLabelsKey.
         * @param {string} [transactionsLabelsValue] This parameter can filter the transactions based on transactionsLabelsValue.
         * @param {string} [walletHashId] Unique wallet identifier generated simultaneously with customer creation.
         * @param {string} [xRequestId] Enter a unique UUID value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async clientTransactions(clientHashId: string, authCode?: string, authCurrency?: string, businessTransaction?: boolean, cardHashId?: string, childCustomerHashId?: string, customerHashId?: string, endDate?: string, mcc?: string, merchantCategories?: string, merchantCity?: string, merchantCountries?: string, merchantCountry?: string, merchantName?: string, order?: ClientTransactionsOrderEnum, page?: number, paymentInstrumentHashId?: string, property?: string, settlementDate?: string, settlementStatus?: string, size?: number, startDate?: string, status?: ClientTransactionsStatusEnum, systemTraceAuditNumber?: string, tagKey?: string, tagValue?: string, transactionCurrency?: string, transactionType?: string, transactionsLabelsKey?: string, transactionsLabelsValue?: string, walletHashId?: string, xRequestId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClientTransactionsResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.clientTransactions(clientHashId, authCode, authCurrency, businessTransaction, cardHashId, childCustomerHashId, customerHashId, endDate, mcc, merchantCategories, merchantCity, merchantCountries, merchantCountry, merchantName, order, page, paymentInstrumentHashId, property, settlementDate, settlementStatus, size, startDate, status, systemTraceAuditNumber, tagKey, tagValue, transactionCurrency, transactionType, transactionsLabelsKey, transactionsLabelsValue, walletHashId, xRequestId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClientTransactionsApi.clientTransactions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ClientTransactionsApi - factory interface
 * @export
 */
export const ClientTransactionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ClientTransactionsApiFp(configuration)
    return {
        /**
         * This API allows you to fetch transaction details at the client level.
         * @summary Client Transactions
         * @param {string} clientHashId Unique client identifier generated and shared before API handshake. &gt;ℹ️ INFO  &gt;Query parameters are optional. If query parameters are not passed then by default three months transactions will be returned.
         * @param {string} [authCode] This parameter can be used to filter the transactions based on the authorization code. In case of fund wallet transactions you can provide the systemReferenceNumber as value.
         * @param {string} [authCurrency] This parameter can filter the transactions based on auth currency and accepts 3-letter [ISO-4217 transaction currency code](https://docs.nium.com/apis/docs/currency-and-country-codes).
         * @param {boolean} [businessTransaction] This parameter can filter the transactions based on businessTransaction flag.
         * @param {string} [cardHashId] This field can apply the filter based on the unique card identifier generated during new/add-on card issuance.
         * @param {string} [childCustomerHashId] This field contains the unique child customer identifier generated when new child customer created.
         * @param {string} [customerHashId] Unique identifier generated with customer creation.
         * @param {string} [endDate] End date for fetching the transaction details. The format for endDate is YYYY-MM-DD.
         * @param {string} [mcc] This parameter can filter the transactions based on 4-digit Merchant Category Codes.
         * @param {string} [merchantCategories] This parameter describes the merchant\&#39;s type of business product or service, also known as the Merchant Category Code (MCC) such as Airlines, Restaurants etc.
         * @param {string} [merchantCity] This parameter can filter the transactions based on the merchant city field.
         * @param {string} [merchantCountries] This parameter can filter the transactions based on comma-separated list of 2-letter ISO merchant countries.
         * @param {string} [merchantCountry] This parameter can filter the transactions based on the merchant country field.
         * @param {string} [merchantName] This parameter can filter the transactions based on the merchant name field.
         * @param {ClientTransactionsOrderEnum} [order] The sort order for the results.
         * @param {number} [page] This API may have lot of data in response and supports pagination. Entire response data is divided into pages with size as the upper limit on the number of data. Integer values from 0 onwards are acceptable. Default page is 0.
         * @param {string} [paymentInstrumentHashId] This parameter can filter the transactions based on comma-separated paymentInstrumentHashId.
         * @param {string} [property] The field indicates the response parameter used to sort paginated data, with \&#39;createdAt\&#39; as the default parameter.
         * @param {string} [settlementDate] This parameter can filter the transactions based on the settlement date of the transaction in format yyyyMMdd.
         * @param {string} [settlementStatus] This parameter can filter the transactions based on settlement status. The detailed list of possible values is available in the response of this API.
         * @param {number} [size] This will decide the number of elements per page. Typical values can be 1-20.
         * @param {string} [startDate] From date for fetching the transaction details. The format for startDate is YYYY-MM-DD.
         * @param {ClientTransactionsStatusEnum} [status] This parameter can filter the transactions based on status. The detailed list of possible values is available in the response of this API.
         * @param {string} [systemTraceAuditNumber] This parameter can filter the transactions based on systemTraceAuditNumber.
         * @param {string} [tagKey] This parameter can filter the transactions, based on the exact value of tagKey defined against transactions. This can be used as an independent search parameter.
         * @param {string} [tagValue] This parameter can filter the transactions, based on the approximating value of tagValue(that may be mapped for a tagKey defined against transactions). This can be used as an independent search parameter.
         * @param {string} [transactionCurrency] This field contains the 3-letter [ISO-4217 transaction currency code](https://www.iso.org/iso-4217-currency-codes.html).
         * @param {string} [transactionType] This field contains the transaction can be one of the complete list of transactions mentioned in [Glossary of Transaction Types](https://docs.nium.com/baas/get-transactions#glossary-of-transaction-types).
         * @param {string} [transactionsLabelsKey] This parameter can filter the transactions based on transactionsLabelsKey.
         * @param {string} [transactionsLabelsValue] This parameter can filter the transactions based on transactionsLabelsValue.
         * @param {string} [walletHashId] Unique wallet identifier generated simultaneously with customer creation.
         * @param {string} [xRequestId] Enter a unique UUID value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        clientTransactions(clientHashId: string, authCode?: string, authCurrency?: string, businessTransaction?: boolean, cardHashId?: string, childCustomerHashId?: string, customerHashId?: string, endDate?: string, mcc?: string, merchantCategories?: string, merchantCity?: string, merchantCountries?: string, merchantCountry?: string, merchantName?: string, order?: ClientTransactionsOrderEnum, page?: number, paymentInstrumentHashId?: string, property?: string, settlementDate?: string, settlementStatus?: string, size?: number, startDate?: string, status?: ClientTransactionsStatusEnum, systemTraceAuditNumber?: string, tagKey?: string, tagValue?: string, transactionCurrency?: string, transactionType?: string, transactionsLabelsKey?: string, transactionsLabelsValue?: string, walletHashId?: string, xRequestId?: string, options?: any): AxiosPromise<ClientTransactionsResponseDTO> {
            return localVarFp.clientTransactions(clientHashId, authCode, authCurrency, businessTransaction, cardHashId, childCustomerHashId, customerHashId, endDate, mcc, merchantCategories, merchantCity, merchantCountries, merchantCountry, merchantName, order, page, paymentInstrumentHashId, property, settlementDate, settlementStatus, size, startDate, status, systemTraceAuditNumber, tagKey, tagValue, transactionCurrency, transactionType, transactionsLabelsKey, transactionsLabelsValue, walletHashId, xRequestId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ClientTransactionsApi - object-oriented interface
 * @export
 * @class ClientTransactionsApi
 * @extends {BaseAPI}
 */
export class ClientTransactionsApi extends BaseAPI {
    /**
     * This API allows you to fetch transaction details at the client level.
     * @summary Client Transactions
     * @param {string} clientHashId Unique client identifier generated and shared before API handshake. &gt;ℹ️ INFO  &gt;Query parameters are optional. If query parameters are not passed then by default three months transactions will be returned.
     * @param {string} [authCode] This parameter can be used to filter the transactions based on the authorization code. In case of fund wallet transactions you can provide the systemReferenceNumber as value.
     * @param {string} [authCurrency] This parameter can filter the transactions based on auth currency and accepts 3-letter [ISO-4217 transaction currency code](https://docs.nium.com/apis/docs/currency-and-country-codes).
     * @param {boolean} [businessTransaction] This parameter can filter the transactions based on businessTransaction flag.
     * @param {string} [cardHashId] This field can apply the filter based on the unique card identifier generated during new/add-on card issuance.
     * @param {string} [childCustomerHashId] This field contains the unique child customer identifier generated when new child customer created.
     * @param {string} [customerHashId] Unique identifier generated with customer creation.
     * @param {string} [endDate] End date for fetching the transaction details. The format for endDate is YYYY-MM-DD.
     * @param {string} [mcc] This parameter can filter the transactions based on 4-digit Merchant Category Codes.
     * @param {string} [merchantCategories] This parameter describes the merchant\&#39;s type of business product or service, also known as the Merchant Category Code (MCC) such as Airlines, Restaurants etc.
     * @param {string} [merchantCity] This parameter can filter the transactions based on the merchant city field.
     * @param {string} [merchantCountries] This parameter can filter the transactions based on comma-separated list of 2-letter ISO merchant countries.
     * @param {string} [merchantCountry] This parameter can filter the transactions based on the merchant country field.
     * @param {string} [merchantName] This parameter can filter the transactions based on the merchant name field.
     * @param {ClientTransactionsOrderEnum} [order] The sort order for the results.
     * @param {number} [page] This API may have lot of data in response and supports pagination. Entire response data is divided into pages with size as the upper limit on the number of data. Integer values from 0 onwards are acceptable. Default page is 0.
     * @param {string} [paymentInstrumentHashId] This parameter can filter the transactions based on comma-separated paymentInstrumentHashId.
     * @param {string} [property] The field indicates the response parameter used to sort paginated data, with \&#39;createdAt\&#39; as the default parameter.
     * @param {string} [settlementDate] This parameter can filter the transactions based on the settlement date of the transaction in format yyyyMMdd.
     * @param {string} [settlementStatus] This parameter can filter the transactions based on settlement status. The detailed list of possible values is available in the response of this API.
     * @param {number} [size] This will decide the number of elements per page. Typical values can be 1-20.
     * @param {string} [startDate] From date for fetching the transaction details. The format for startDate is YYYY-MM-DD.
     * @param {ClientTransactionsStatusEnum} [status] This parameter can filter the transactions based on status. The detailed list of possible values is available in the response of this API.
     * @param {string} [systemTraceAuditNumber] This parameter can filter the transactions based on systemTraceAuditNumber.
     * @param {string} [tagKey] This parameter can filter the transactions, based on the exact value of tagKey defined against transactions. This can be used as an independent search parameter.
     * @param {string} [tagValue] This parameter can filter the transactions, based on the approximating value of tagValue(that may be mapped for a tagKey defined against transactions). This can be used as an independent search parameter.
     * @param {string} [transactionCurrency] This field contains the 3-letter [ISO-4217 transaction currency code](https://www.iso.org/iso-4217-currency-codes.html).
     * @param {string} [transactionType] This field contains the transaction can be one of the complete list of transactions mentioned in [Glossary of Transaction Types](https://docs.nium.com/baas/get-transactions#glossary-of-transaction-types).
     * @param {string} [transactionsLabelsKey] This parameter can filter the transactions based on transactionsLabelsKey.
     * @param {string} [transactionsLabelsValue] This parameter can filter the transactions based on transactionsLabelsValue.
     * @param {string} [walletHashId] Unique wallet identifier generated simultaneously with customer creation.
     * @param {string} [xRequestId] Enter a unique UUID value
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClientTransactionsApi
     */
    public clientTransactions(clientHashId: string, authCode?: string, authCurrency?: string, businessTransaction?: boolean, cardHashId?: string, childCustomerHashId?: string, customerHashId?: string, endDate?: string, mcc?: string, merchantCategories?: string, merchantCity?: string, merchantCountries?: string, merchantCountry?: string, merchantName?: string, order?: ClientTransactionsOrderEnum, page?: number, paymentInstrumentHashId?: string, property?: string, settlementDate?: string, settlementStatus?: string, size?: number, startDate?: string, status?: ClientTransactionsStatusEnum, systemTraceAuditNumber?: string, tagKey?: string, tagValue?: string, transactionCurrency?: string, transactionType?: string, transactionsLabelsKey?: string, transactionsLabelsValue?: string, walletHashId?: string, xRequestId?: string, options?: RawAxiosRequestConfig) {
        return ClientTransactionsApiFp(this.configuration).clientTransactions(clientHashId, authCode, authCurrency, businessTransaction, cardHashId, childCustomerHashId, customerHashId, endDate, mcc, merchantCategories, merchantCity, merchantCountries, merchantCountry, merchantName, order, page, paymentInstrumentHashId, property, settlementDate, settlementStatus, size, startDate, status, systemTraceAuditNumber, tagKey, tagValue, transactionCurrency, transactionType, transactionsLabelsKey, transactionsLabelsValue, walletHashId, xRequestId, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const ClientTransactionsOrderEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type ClientTransactionsOrderEnum = typeof ClientTransactionsOrderEnum[keyof typeof ClientTransactionsOrderEnum];
/**
 * @export
 */
export const ClientTransactionsStatusEnum = {
    Null: 'NULL',
    InProgress: 'IN_PROGRESS',
    ActionRequired: 'ACTION_REQUIRED',
    RfiRequested: 'RFI_REQUESTED',
    RfiResponded: 'RFI_RESPONDED',
    Completed: 'COMPLETED',
    Error: 'ERROR',
    Reject: 'REJECT',
    Expired: 'EXPIRED'
} as const;
export type ClientTransactionsStatusEnum = typeof ClientTransactionsStatusEnum[keyof typeof ClientTransactionsStatusEnum];
