/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2026.4.14
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DocumentStorageServiceErrorResponse403 } from '../model';
// @ts-ignore
import type { DocumentStorageServiceErrorResponse500 } from '../model';
// @ts-ignore
import type { ErrorResponse400Upload } from '../model';
// @ts-ignore
import type { FileCreationRequest } from '../model';
// @ts-ignore
import type { FileCreationResponse } from '../model';
// @ts-ignore
import type { FileMetadata } from '../model';
/**
 * FilesApi - axios parameter creator
 */
export const FilesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a `file` resource.
         * @summary Create a File
         * @param {string} clientHashId 
         * @param {string} [xApiKey] 
         * @param {string} [xRequestId] Enter a unique UUID value.
         * @param {string} [xNformifyOnboarding] 
         * @param {FileCreationRequest} [metadata] 
         * @param {File} [file] The file to upload (required)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createFileDocContext1: async (clientHashId: string, xApiKey?: string, xRequestId?: string, xNformifyOnboarding?: string, metadata?: FileCreationRequest, file?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientHashId' is not null or undefined
            assertParamExists('createFileDocContext1', 'clientHashId', clientHashId)
            const localVarPath = `/api/v1/client/{clientHashId}/files`
                .replace(`{${"clientHashId"}}`, encodeURIComponent(String(clientHashId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication default required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


            if (metadata !== undefined) { 
                localVarFormParams.append('metadata', new Blob([JSON.stringify(metadata, replaceWithSerializableTypeIfNeeded)], { type: "application/json", }));
            }

            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json,*/*';

            if (xApiKey != null) {
                localVarHeaderParameter['x-api-key'] = String(xApiKey);
            }
            if (xRequestId != null) {
                localVarHeaderParameter['x-request-id'] = String(xRequestId);
            }
            if (xNformifyOnboarding != null) {
                localVarHeaderParameter['X-Nformify-Onboarding'] = String(xNformifyOnboarding);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch the metadata of a specific `file`.
         * @summary Fetch File Details
         * @param {string} clientHashId 
         * @param {string} fileId 
         * @param {string} [xApiKey] 
         * @param {string} [xRequestId] Enter a universally unique identifier (UUID).
         * @param {string} [xNformifyOnboarding] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchFileMetadataDocContext1: async (clientHashId: string, fileId: string, xApiKey?: string, xRequestId?: string, xNformifyOnboarding?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientHashId' is not null or undefined
            assertParamExists('fetchFileMetadataDocContext1', 'clientHashId', clientHashId)
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('fetchFileMetadataDocContext1', 'fileId', fileId)
            const localVarPath = `/api/v1/client/{clientHashId}/files/{fileId}`
                .replace(`{${"clientHashId"}}`, encodeURIComponent(String(clientHashId)))
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication default required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json,*/*';

            if (xApiKey != null) {
                localVarHeaderParameter['x-api-key'] = String(xApiKey);
            }
            if (xRequestId != null) {
                localVarHeaderParameter['x-request-id'] = String(xRequestId);
            }
            if (xNformifyOnboarding != null) {
                localVarHeaderParameter['X-Nformify-Onboarding'] = String(xNformifyOnboarding);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FilesApi - functional programming interface
 */
export const FilesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FilesApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a `file` resource.
         * @summary Create a File
         * @param {string} clientHashId 
         * @param {string} [xApiKey] 
         * @param {string} [xRequestId] Enter a unique UUID value.
         * @param {string} [xNformifyOnboarding] 
         * @param {FileCreationRequest} [metadata] 
         * @param {File} [file] The file to upload (required)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createFileDocContext1(clientHashId: string, xApiKey?: string, xRequestId?: string, xNformifyOnboarding?: string, metadata?: FileCreationRequest, file?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileCreationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createFileDocContext1(clientHashId, xApiKey, xRequestId, xNformifyOnboarding, metadata, file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.createFileDocContext1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch the metadata of a specific `file`.
         * @summary Fetch File Details
         * @param {string} clientHashId 
         * @param {string} fileId 
         * @param {string} [xApiKey] 
         * @param {string} [xRequestId] Enter a universally unique identifier (UUID).
         * @param {string} [xNformifyOnboarding] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchFileMetadataDocContext1(clientHashId: string, fileId: string, xApiKey?: string, xRequestId?: string, xNformifyOnboarding?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileMetadata>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchFileMetadataDocContext1(clientHashId, fileId, xApiKey, xRequestId, xNformifyOnboarding, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.fetchFileMetadataDocContext1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FilesApi - factory interface
 */
export const FilesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FilesApiFp(configuration)
    return {
        /**
         * Creates a `file` resource.
         * @summary Create a File
         * @param {FilesApiCreateFileDocContext1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createFileDocContext1(requestParameters: FilesApiCreateFileDocContext1Request, options?: RawAxiosRequestConfig): AxiosPromise<FileCreationResponse> {
            return localVarFp.createFileDocContext1(requestParameters.clientHashId, requestParameters.xApiKey, requestParameters.xRequestId, requestParameters.xNformifyOnboarding, requestParameters.metadata, requestParameters.file, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch the metadata of a specific `file`.
         * @summary Fetch File Details
         * @param {FilesApiFetchFileMetadataDocContext1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchFileMetadataDocContext1(requestParameters: FilesApiFetchFileMetadataDocContext1Request, options?: RawAxiosRequestConfig): AxiosPromise<FileMetadata> {
            return localVarFp.fetchFileMetadataDocContext1(requestParameters.clientHashId, requestParameters.fileId, requestParameters.xApiKey, requestParameters.xRequestId, requestParameters.xNformifyOnboarding, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createFileDocContext1 operation in FilesApi.
 */
export interface FilesApiCreateFileDocContext1Request {
    readonly clientHashId: string

    readonly xApiKey?: string

    /**
     * Enter a unique UUID value.
     */
    readonly xRequestId?: string

    readonly xNformifyOnboarding?: string

    readonly metadata?: FileCreationRequest

    /**
     * The file to upload (required)
     */
    readonly file?: File
}

/**
 * Request parameters for fetchFileMetadataDocContext1 operation in FilesApi.
 */
export interface FilesApiFetchFileMetadataDocContext1Request {
    readonly clientHashId: string

    readonly fileId: string

    readonly xApiKey?: string

    /**
     * Enter a universally unique identifier (UUID).
     */
    readonly xRequestId?: string

    readonly xNformifyOnboarding?: string
}

/**
 * FilesApi - object-oriented interface
 */
export class FilesApi extends BaseAPI {
    /**
     * Creates a `file` resource.
     * @summary Create a File
     * @param {FilesApiCreateFileDocContext1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createFileDocContext1(requestParameters: FilesApiCreateFileDocContext1Request, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).createFileDocContext1(requestParameters.clientHashId, requestParameters.xApiKey, requestParameters.xRequestId, requestParameters.xNformifyOnboarding, requestParameters.metadata, requestParameters.file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch the metadata of a specific `file`.
     * @summary Fetch File Details
     * @param {FilesApiFetchFileMetadataDocContext1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fetchFileMetadataDocContext1(requestParameters: FilesApiFetchFileMetadataDocContext1Request, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).fetchFileMetadataDocContext1(requestParameters.clientHashId, requestParameters.fileId, requestParameters.xApiKey, requestParameters.xRequestId, requestParameters.xNformifyOnboarding, options).then((request) => request(this.axios, this.basePath));
    }
}

