/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2026.4.14
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GenerateLinkRequest } from '../model';
// @ts-ignore
import type { GenerateLinkResponse } from '../model';
// @ts-ignore
import type { OnboardingApplicationProgressResponse } from '../model';
// @ts-ignore
import type { OnboardingFormServiceApiErrorResponse } from '../model';
// @ts-ignore
import type { OnboardingFormServiceStandard404Error } from '../model';
// @ts-ignore
import type { Standard401Error } from '../model';
// @ts-ignore
import type { Standard500Error } from '../model';
/**
 * OnboardingFormsCorporateApi - axios parameter creator
 */
export const OnboardingFormsCorporateApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve the details of a given application onboarded using an onboarding form.
         * @summary Fetch Application Details
         * @param {string} applicationId Application ID generated for the customer.
         * @param {string} clientHashId Unique client identifier generated and shared before the initial request.
         * @param {string} [xRequestId] Enter a universally unique identifier (UUID).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApplicationDetails: async (applicationId: string, clientHashId: string, xRequestId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'applicationId' is not null or undefined
            assertParamExists('getApplicationDetails', 'applicationId', applicationId)
            // verify required parameter 'clientHashId' is not null or undefined
            assertParamExists('getApplicationDetails', 'clientHashId', clientHashId)
            const localVarPath = `/api/v1/client/{clientHashId}/application/{applicationId}`
                .replace(`{${"applicationId"}}`, encodeURIComponent(String(applicationId)))
                .replace(`{${"clientHashId"}}`, encodeURIComponent(String(clientHashId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication default required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRequestId != null) {
                localVarHeaderParameter['x-request-id'] = String(xRequestId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create an application and generate links for customers to access onboarding forms. For more information, see [Onboarding Forms](/docs/onboarding-forms).
         * @summary Create Application for Onboarding Form
         * @param {string} clientHashId Unique client identifier generated and shared before the initial request.
         * @param {GenerateLinkRequest} generateLinkRequest 
         * @param {string} [xRequestId] Enter a universally unique identifier (UUID).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        onboardingFormLink: async (clientHashId: string, generateLinkRequest: GenerateLinkRequest, xRequestId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientHashId' is not null or undefined
            assertParamExists('onboardingFormLink', 'clientHashId', clientHashId)
            // verify required parameter 'generateLinkRequest' is not null or undefined
            assertParamExists('onboardingFormLink', 'generateLinkRequest', generateLinkRequest)
            const localVarPath = `/api/v1/client/{clientHashId}/applications`
                .replace(`{${"clientHashId"}}`, encodeURIComponent(String(clientHashId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication default required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRequestId != null) {
                localVarHeaderParameter['x-request-id'] = String(xRequestId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(generateLinkRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Generates a link for the customer to the onboarding form if the previous link expires.
         * @summary Regenerate Onboarding Form URL
         * @param {string} applicationId Application ID returned in response while creating an application. resource.
         * @param {string} clientHashId Unique client identifier generated and shared before the initial request.
         * @param {string} [xRequestId] Enter a universally unique identifier (UUID).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regenerateURL: async (applicationId: string, clientHashId: string, xRequestId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'applicationId' is not null or undefined
            assertParamExists('regenerateURL', 'applicationId', applicationId)
            // verify required parameter 'clientHashId' is not null or undefined
            assertParamExists('regenerateURL', 'clientHashId', clientHashId)
            const localVarPath = `/api/v1/client/{clientHashId}/applications/{applicationId}/regenerateURL`
                .replace(`{${"applicationId"}}`, encodeURIComponent(String(applicationId)))
                .replace(`{${"clientHashId"}}`, encodeURIComponent(String(clientHashId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication default required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRequestId != null) {
                localVarHeaderParameter['x-request-id'] = String(xRequestId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OnboardingFormsCorporateApi - functional programming interface
 */
export const OnboardingFormsCorporateApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OnboardingFormsCorporateApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve the details of a given application onboarded using an onboarding form.
         * @summary Fetch Application Details
         * @param {string} applicationId Application ID generated for the customer.
         * @param {string} clientHashId Unique client identifier generated and shared before the initial request.
         * @param {string} [xRequestId] Enter a universally unique identifier (UUID).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getApplicationDetails(applicationId: string, clientHashId: string, xRequestId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OnboardingApplicationProgressResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getApplicationDetails(applicationId, clientHashId, xRequestId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OnboardingFormsCorporateApi.getApplicationDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create an application and generate links for customers to access onboarding forms. For more information, see [Onboarding Forms](/docs/onboarding-forms).
         * @summary Create Application for Onboarding Form
         * @param {string} clientHashId Unique client identifier generated and shared before the initial request.
         * @param {GenerateLinkRequest} generateLinkRequest 
         * @param {string} [xRequestId] Enter a universally unique identifier (UUID).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async onboardingFormLink(clientHashId: string, generateLinkRequest: GenerateLinkRequest, xRequestId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenerateLinkResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.onboardingFormLink(clientHashId, generateLinkRequest, xRequestId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OnboardingFormsCorporateApi.onboardingFormLink']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Generates a link for the customer to the onboarding form if the previous link expires.
         * @summary Regenerate Onboarding Form URL
         * @param {string} applicationId Application ID returned in response while creating an application. resource.
         * @param {string} clientHashId Unique client identifier generated and shared before the initial request.
         * @param {string} [xRequestId] Enter a universally unique identifier (UUID).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async regenerateURL(applicationId: string, clientHashId: string, xRequestId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenerateLinkResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.regenerateURL(applicationId, clientHashId, xRequestId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OnboardingFormsCorporateApi.regenerateURL']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OnboardingFormsCorporateApi - factory interface
 */
export const OnboardingFormsCorporateApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OnboardingFormsCorporateApiFp(configuration)
    return {
        /**
         * Retrieve the details of a given application onboarded using an onboarding form.
         * @summary Fetch Application Details
         * @param {OnboardingFormsCorporateApiGetApplicationDetailsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApplicationDetails(requestParameters: OnboardingFormsCorporateApiGetApplicationDetailsRequest, options?: RawAxiosRequestConfig): AxiosPromise<OnboardingApplicationProgressResponse> {
            return localVarFp.getApplicationDetails(requestParameters.applicationId, requestParameters.clientHashId, requestParameters.xRequestId, options).then((request) => request(axios, basePath));
        },
        /**
         * Create an application and generate links for customers to access onboarding forms. For more information, see [Onboarding Forms](/docs/onboarding-forms).
         * @summary Create Application for Onboarding Form
         * @param {OnboardingFormsCorporateApiOnboardingFormLinkRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        onboardingFormLink(requestParameters: OnboardingFormsCorporateApiOnboardingFormLinkRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenerateLinkResponse> {
            return localVarFp.onboardingFormLink(requestParameters.clientHashId, requestParameters.generateLinkRequest, requestParameters.xRequestId, options).then((request) => request(axios, basePath));
        },
        /**
         * Generates a link for the customer to the onboarding form if the previous link expires.
         * @summary Regenerate Onboarding Form URL
         * @param {OnboardingFormsCorporateApiRegenerateURLRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regenerateURL(requestParameters: OnboardingFormsCorporateApiRegenerateURLRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenerateLinkResponse> {
            return localVarFp.regenerateURL(requestParameters.applicationId, requestParameters.clientHashId, requestParameters.xRequestId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getApplicationDetails operation in OnboardingFormsCorporateApi.
 */
export interface OnboardingFormsCorporateApiGetApplicationDetailsRequest {
    /**
     * Application ID generated for the customer.
     */
    readonly applicationId: string

    /**
     * Unique client identifier generated and shared before the initial request.
     */
    readonly clientHashId: string

    /**
     * Enter a universally unique identifier (UUID).
     */
    readonly xRequestId?: string
}

/**
 * Request parameters for onboardingFormLink operation in OnboardingFormsCorporateApi.
 */
export interface OnboardingFormsCorporateApiOnboardingFormLinkRequest {
    /**
     * Unique client identifier generated and shared before the initial request.
     */
    readonly clientHashId: string

    readonly generateLinkRequest: GenerateLinkRequest

    /**
     * Enter a universally unique identifier (UUID).
     */
    readonly xRequestId?: string
}

/**
 * Request parameters for regenerateURL operation in OnboardingFormsCorporateApi.
 */
export interface OnboardingFormsCorporateApiRegenerateURLRequest {
    /**
     * Application ID returned in response while creating an application. resource.
     */
    readonly applicationId: string

    /**
     * Unique client identifier generated and shared before the initial request.
     */
    readonly clientHashId: string

    /**
     * Enter a universally unique identifier (UUID).
     */
    readonly xRequestId?: string
}

/**
 * OnboardingFormsCorporateApi - object-oriented interface
 */
export class OnboardingFormsCorporateApi extends BaseAPI {
    /**
     * Retrieve the details of a given application onboarded using an onboarding form.
     * @summary Fetch Application Details
     * @param {OnboardingFormsCorporateApiGetApplicationDetailsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getApplicationDetails(requestParameters: OnboardingFormsCorporateApiGetApplicationDetailsRequest, options?: RawAxiosRequestConfig) {
        return OnboardingFormsCorporateApiFp(this.configuration).getApplicationDetails(requestParameters.applicationId, requestParameters.clientHashId, requestParameters.xRequestId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create an application and generate links for customers to access onboarding forms. For more information, see [Onboarding Forms](/docs/onboarding-forms).
     * @summary Create Application for Onboarding Form
     * @param {OnboardingFormsCorporateApiOnboardingFormLinkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public onboardingFormLink(requestParameters: OnboardingFormsCorporateApiOnboardingFormLinkRequest, options?: RawAxiosRequestConfig) {
        return OnboardingFormsCorporateApiFp(this.configuration).onboardingFormLink(requestParameters.clientHashId, requestParameters.generateLinkRequest, requestParameters.xRequestId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Generates a link for the customer to the onboarding form if the previous link expires.
     * @summary Regenerate Onboarding Form URL
     * @param {OnboardingFormsCorporateApiRegenerateURLRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public regenerateURL(requestParameters: OnboardingFormsCorporateApiRegenerateURLRequest, options?: RawAxiosRequestConfig) {
        return OnboardingFormsCorporateApiFp(this.configuration).regenerateURL(requestParameters.applicationId, requestParameters.clientHashId, requestParameters.xRequestId, options).then((request) => request(this.axios, this.basePath));
    }
}

