/* tslint:disable */
/* eslint-disable */
/**
 * Nium API Reference
 * The Nium API is a RESTful platform that helps you build and scale global financial services including payouts, foreign exchange, onboarding, and digital wallets. It offers secure, resource-oriented endpoints for onboarding, wallet management, foreign exchange, payments, compliance, and more.  Built on standard REST principles, the Nium API uses **JSON-formatted requests and responses**, **HTTPS** for secure communication, and consistent conventions across all endpoints. Each integration is modular—so you can implement only what you need—and reliable, so your team can move fast with confidence.  You can use the Nium API to:   - Onboard individual or corporate customers with built-in **KYC/KYB** workflows.   - Manage digital wallets and transfer funds in real time.   - Access competitive **foreign exchange (FX)** rates and lock them securely.   - Make global payouts via bank transfers, cards, and local payment methods.   - Prefund and reconcile transactions for operational control.   - Monitor transactions and generate account statements.   - Handle compliance with document uploads and **RFI (Request for Information)** flows.    This reference includes everything you need to get started, including request and response structures, required headers, code samples, and schema definitions.        For more information about using Nium, see [Nium Documentation](/).
 *
 * The version of the OpenAPI document: 2026.4.14
 * Contact: experience@nium.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { FundingInstrumentStatusUpdateRequestDTO } from '../model';
// @ts-ignore
import type { InwardPaymentManualRequestDTO } from '../model';
// @ts-ignore
import type { PayinApiError } from '../model';
// @ts-ignore
import type { PayinApiResponse2 } from '../model';
/**
 * PayinApi - axios parameter creator
 */
export const PayinApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Test the status change of a funding instrument. For more information, see [Testing Nium](/docs/testing).
         * @summary Simulate Funding Instrument Status Update (Sandbox Testing)
         * @param {string} clientHashId clientHashId
         * @param {string} customerHashId customerHashId
         * @param {string} fundingInstrumentId fundingInstrumentId
         * @param {FundingInstrumentStatusUpdateRequestDTO} fundingInstrumentStatusUpdateRequestDTO Funding Instrument - Status Update Request
         * @param {string} [xRequestId] Enter a universally unique identifier (UUID).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulateFundingInstrumentStatusUpdate: async (clientHashId: string, customerHashId: string, fundingInstrumentId: string, fundingInstrumentStatusUpdateRequestDTO: FundingInstrumentStatusUpdateRequestDTO, xRequestId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientHashId' is not null or undefined
            assertParamExists('simulateFundingInstrumentStatusUpdate', 'clientHashId', clientHashId)
            // verify required parameter 'customerHashId' is not null or undefined
            assertParamExists('simulateFundingInstrumentStatusUpdate', 'customerHashId', customerHashId)
            // verify required parameter 'fundingInstrumentId' is not null or undefined
            assertParamExists('simulateFundingInstrumentStatusUpdate', 'fundingInstrumentId', fundingInstrumentId)
            // verify required parameter 'fundingInstrumentStatusUpdateRequestDTO' is not null or undefined
            assertParamExists('simulateFundingInstrumentStatusUpdate', 'fundingInstrumentStatusUpdateRequestDTO', fundingInstrumentStatusUpdateRequestDTO)
            const localVarPath = `/api/v1/simulations/client/{clientHashId}/customer/{customerHashId}/fundingInstruments/{fundingInstrumentId}/updateStatus`
                .replace(`{${"clientHashId"}}`, encodeURIComponent(String(clientHashId)))
                .replace(`{${"customerHashId"}}`, encodeURIComponent(String(customerHashId)))
                .replace(`{${"fundingInstrumentId"}}`, encodeURIComponent(String(fundingInstrumentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication default required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRequestId != null) {
                localVarHeaderParameter['x-request-id'] = String(xRequestId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fundingInstrumentStatusUpdateRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Test receiving a transaction. For more information, see [Testing Nium](/docs/testing).
         * @summary Simulate Receiving a Transaction
         * @param {InwardPaymentManualRequestDTO} inwardPaymentManualRequestDTO Manual Inward Payment Request
         * @param {string} [xRequestId] Enter a universally unique identifier (UUID).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulatereceivepayment: async (inwardPaymentManualRequestDTO: InwardPaymentManualRequestDTO, xRequestId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'inwardPaymentManualRequestDTO' is not null or undefined
            assertParamExists('simulatereceivepayment', 'inwardPaymentManualRequestDTO', inwardPaymentManualRequestDTO)
            const localVarPath = `/api/v1/inward/payment/manual`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication default required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRequestId != null) {
                localVarHeaderParameter['x-request-id'] = String(xRequestId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(inwardPaymentManualRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PayinApi - functional programming interface
 */
export const PayinApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PayinApiAxiosParamCreator(configuration)
    return {
        /**
         * Test the status change of a funding instrument. For more information, see [Testing Nium](/docs/testing).
         * @summary Simulate Funding Instrument Status Update (Sandbox Testing)
         * @param {string} clientHashId clientHashId
         * @param {string} customerHashId customerHashId
         * @param {string} fundingInstrumentId fundingInstrumentId
         * @param {FundingInstrumentStatusUpdateRequestDTO} fundingInstrumentStatusUpdateRequestDTO Funding Instrument - Status Update Request
         * @param {string} [xRequestId] Enter a universally unique identifier (UUID).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async simulateFundingInstrumentStatusUpdate(clientHashId: string, customerHashId: string, fundingInstrumentId: string, fundingInstrumentStatusUpdateRequestDTO: FundingInstrumentStatusUpdateRequestDTO, xRequestId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.simulateFundingInstrumentStatusUpdate(clientHashId, customerHashId, fundingInstrumentId, fundingInstrumentStatusUpdateRequestDTO, xRequestId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PayinApi.simulateFundingInstrumentStatusUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Test receiving a transaction. For more information, see [Testing Nium](/docs/testing).
         * @summary Simulate Receiving a Transaction
         * @param {InwardPaymentManualRequestDTO} inwardPaymentManualRequestDTO Manual Inward Payment Request
         * @param {string} [xRequestId] Enter a universally unique identifier (UUID).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async simulatereceivepayment(inwardPaymentManualRequestDTO: InwardPaymentManualRequestDTO, xRequestId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PayinApiResponse2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.simulatereceivepayment(inwardPaymentManualRequestDTO, xRequestId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PayinApi.simulatereceivepayment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PayinApi - factory interface
 */
export const PayinApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PayinApiFp(configuration)
    return {
        /**
         * Test the status change of a funding instrument. For more information, see [Testing Nium](/docs/testing).
         * @summary Simulate Funding Instrument Status Update (Sandbox Testing)
         * @param {PayinApiSimulateFundingInstrumentStatusUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulateFundingInstrumentStatusUpdate(requestParameters: PayinApiSimulateFundingInstrumentStatusUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.simulateFundingInstrumentStatusUpdate(requestParameters.clientHashId, requestParameters.customerHashId, requestParameters.fundingInstrumentId, requestParameters.fundingInstrumentStatusUpdateRequestDTO, requestParameters.xRequestId, options).then((request) => request(axios, basePath));
        },
        /**
         * Test receiving a transaction. For more information, see [Testing Nium](/docs/testing).
         * @summary Simulate Receiving a Transaction
         * @param {PayinApiSimulatereceivepaymentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        simulatereceivepayment(requestParameters: PayinApiSimulatereceivepaymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<PayinApiResponse2> {
            return localVarFp.simulatereceivepayment(requestParameters.inwardPaymentManualRequestDTO, requestParameters.xRequestId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for simulateFundingInstrumentStatusUpdate operation in PayinApi.
 */
export interface PayinApiSimulateFundingInstrumentStatusUpdateRequest {
    /**
     * clientHashId
     */
    readonly clientHashId: string

    /**
     * customerHashId
     */
    readonly customerHashId: string

    /**
     * fundingInstrumentId
     */
    readonly fundingInstrumentId: string

    /**
     * Funding Instrument - Status Update Request
     */
    readonly fundingInstrumentStatusUpdateRequestDTO: FundingInstrumentStatusUpdateRequestDTO

    /**
     * Enter a universally unique identifier (UUID).
     */
    readonly xRequestId?: string
}

/**
 * Request parameters for simulatereceivepayment operation in PayinApi.
 */
export interface PayinApiSimulatereceivepaymentRequest {
    /**
     * Manual Inward Payment Request
     */
    readonly inwardPaymentManualRequestDTO: InwardPaymentManualRequestDTO

    /**
     * Enter a universally unique identifier (UUID).
     */
    readonly xRequestId?: string
}

/**
 * PayinApi - object-oriented interface
 */
export class PayinApi extends BaseAPI {
    /**
     * Test the status change of a funding instrument. For more information, see [Testing Nium](/docs/testing).
     * @summary Simulate Funding Instrument Status Update (Sandbox Testing)
     * @param {PayinApiSimulateFundingInstrumentStatusUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public simulateFundingInstrumentStatusUpdate(requestParameters: PayinApiSimulateFundingInstrumentStatusUpdateRequest, options?: RawAxiosRequestConfig) {
        return PayinApiFp(this.configuration).simulateFundingInstrumentStatusUpdate(requestParameters.clientHashId, requestParameters.customerHashId, requestParameters.fundingInstrumentId, requestParameters.fundingInstrumentStatusUpdateRequestDTO, requestParameters.xRequestId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Test receiving a transaction. For more information, see [Testing Nium](/docs/testing).
     * @summary Simulate Receiving a Transaction
     * @param {PayinApiSimulatereceivepaymentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public simulatereceivepayment(requestParameters: PayinApiSimulatereceivepaymentRequest, options?: RawAxiosRequestConfig) {
        return PayinApiFp(this.configuration).simulatereceivepayment(requestParameters.inwardPaymentManualRequestDTO, requestParameters.xRequestId, options).then((request) => request(this.axios, this.basePath));
    }
}

